{
 "title": "Nginx Access Logs Analysis",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Geodistribution of Web Requests",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT date_time_string, ipv4_num_to_string_class_c(nal.remote_ip) as remote_ip, nip.country_name as country, nip.country_flag_emoji as emoji, nip.loc as loc, \ngeohash_encode(to_float64(split_by_char(',', loc)[2]), to_float64(split_by_char(',', loc)[1])) as geohash \nFROM table(nginx_historical_access_log) as nal JOIN table(nginx_ipinfo) as nip ON nal.remote_ip = nip.ip WHERE NOT empty(loc) \nGROUP BY remote_ip, date_time_string, country, emoji, loc HAVING count() > 0 ORDER BY date_time_string DESC;\n"
    }
   ]
  },
  {
   "title": "Geolocation",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT date_time_string, ipv4_num_to_string_class_c(nal.remote_ip) as remote_ip, nip.country_name as country, nip.country_flag_emoji as emoji, nip.loc as loc, \ngeohash_encode(to_float64(split_by_char(',', loc)[2]), to_float64(split_by_char(',', loc)[1])) as geohash \nFROM table(nginx_historical_access_log) as nal JOIN table(nginx_ipinfo) as nip ON nal.remote_ip = nip.ip WHERE NOT empty(loc) \nGROUP BY remote_ip, date_time_string, country, emoji, loc HAVING count() > 0 ORDER BY date_time_string DESC LIMIT 50;\n"
    }
   ]
  },
  {
   "title": "Top Traffic Sources",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT count() as page_views, nip.country_name as country, nip.country_flag_emoji as emoji \nFROM table(nginx_historical_access_log) as nal \nJOIN table(nginx_ipinfo) as nip ON nal.remote_ip = nip.ip \nGROUP BY country, emoji HAVING count() > 0 ORDER BY page_views DESC;"
    }
   ]
  },
  {
   "title": "Page Traffic",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "queryText": "SELECT path, count() as request_count\nFROM table(nginx_historical_access_log)\nWHERE (path NOT LIKE '%.js%')\n    AND (path NOT LIKE '%.css%')\n    AND (path NOT LIKE '%.png%')\n    AND (path NOT LIKE '%.gif%')\n    AND (path NOT LIKE '%.jpg')\nGROUP BY path\nORDER BY count() DESC;"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "queryText": "SELECT\n    multi_if(status >= 400, '40x - Error', status > 300, '30x - Notice', '200 - OK') AS status_code,\n    count() as frequency\nFROM table(nginx_historical_access_log)\nGROUP BY status_code;\n"
    }
   ]
  }
 ]
}