SET query_mode = 'table';
drop stream if exists T;
create stream T(a Nullable(int64)) engine = Memory();
insert into T values (1), (2), (3), (4), (5);
select sum_if(42, (a % 2) = 0) from T;
select sum_if(42, (a % 2) = 0) from remote('127.0.0.{1,2}', currentDatabase(), T);
select sum_if(42, to_nullable(1)) from T;
select sum_if(42, to_nullable(1)) from remote('127.0.0.{1,2}', currentDatabase(), T);
-- select sum_if(42, to_nullable(to_int64(1))) from T;
-- select sum_if(42, to_nullable(to_int64(1))) from remote('127.0.0.{1,2}', currentDatabase(), T);
drop stream if exists T;
