/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* This code was generated by avrogencpp 1.11.3. Do not edit.*/

#pragma once

#include <avro/Decoder.hh>
#include <avro/Encoder.hh>
#include <avro/Specific.hh>

#include <any>

namespace Apache::Iceberg
{
struct r508_contains_nan
{
private:
    size_t idx_;
    std::any value_;

public:
    size_t idx() const { return idx_; }
    bool is_null() const { return (idx_ == 0); }
    void set_null()
    {
        idx_ = 0;
        value_ = std::any();
    }
    bool get_bool() const;
    void set_bool(const bool & v);
    r508_contains_nan();
};

struct r508_lower_bound
{
private:
    size_t idx_;
    std::any value_;

public:
    size_t idx() const { return idx_; }
    bool is_null() const { return (idx_ == 0); }
    void set_null()
    {
        idx_ = 0;
        value_ = std::any();
    }
    std::vector<uint8_t> get_bytes() const;
    void set_bytes(const std::vector<uint8_t> & v);
    r508_lower_bound();
};

struct r508_upper_bound
{
private:
    size_t idx_;
    std::any value_;

public:
    size_t idx() const { return idx_; }
    bool is_null() const { return (idx_ == 0); }
    void set_null()
    {
        idx_ = 0;
        value_ = std::any();
    }
    std::vector<uint8_t> get_bytes() const;
    void set_bytes(const std::vector<uint8_t> & v);
    r508_upper_bound();
};

struct r508
{
    bool contains_null;
    r508_contains_nan contains_nan;
    r508_lower_bound lower_bound;
    r508_upper_bound upper_bound;
    r508() : contains_null(bool()) { }
};

struct partitions
{
private:
    size_t idx_;
    std::any value_;

public:
    size_t idx() const { return idx_; }
    bool is_null() const { return (idx_ == 0); }
    void set_null()
    {
        idx_ = 0;
        value_ = std::any();
    }
    std::vector<r508> get_array() const;
    void set_array(const std::vector<r508> & v);
    partitions();
};

struct key_metadata
{
private:
    size_t idx_;
    std::any value_;

public:
    size_t idx() const { return idx_; }
    bool is_null() const { return (idx_ == 0); }
    void set_null()
    {
        idx_ = 0;
        value_ = std::any();
    }
    std::vector<uint8_t> get_bytes() const;
    void set_bytes(const std::vector<uint8_t> & v);
    key_metadata();
};

struct ManifestList
{
    std::string manifest_path;
    int64_t manifest_length;
    int32_t partition_spec_id;
    int32_t content;
    int64_t sequence_number;
    int64_t min_sequence_number;
    int64_t added_snapshot_id;
    int32_t added_files_count;
    int32_t existing_files_count;
    int32_t deleted_files_count;
    int64_t added_rows_count;
    int64_t existing_rows_count;
    int64_t deleted_rows_count;
    partitions partitions;
    key_metadata key_metadata;
    ManifestList()
        : manifest_length(int64_t())
        , partition_spec_id(int32_t())
        , content(int32_t())
        , sequence_number(int64_t())
        , min_sequence_number(int64_t())
        , added_snapshot_id(int64_t())
        , added_files_count(int32_t())
        , existing_files_count(int32_t())
        , deleted_files_count(int32_t())
        , added_rows_count(int64_t())
        , existing_rows_count(int64_t())
        , deleted_rows_count(int64_t())
    {
    }
};

inline bool r508_contains_nan::get_bool() const
{
    if (idx_ != 1)
    {
        throw avro::Exception("Invalid type for union r508_contains_nan");
    }
    return std::any_cast<bool>(value_);
}

inline void r508_contains_nan::set_bool(const bool & v)
{
    idx_ = 1;
    value_ = v;
}

inline std::vector<uint8_t> r508_lower_bound::get_bytes() const
{
    if (idx_ != 1)
    {
        throw avro::Exception("Invalid type for union r508_lower_bound");
    }
    return std::any_cast<std::vector<uint8_t>>(value_);
}

inline void r508_lower_bound::set_bytes(const std::vector<uint8_t> & v)
{
    idx_ = 1;
    value_ = v;
}

inline std::vector<uint8_t> r508_upper_bound::get_bytes() const
{
    if (idx_ != 1)
    {
        throw avro::Exception("Invalid type for union r508_upper_bound");
    }
    return std::any_cast<std::vector<uint8_t>>(value_);
}

inline void r508_upper_bound::set_bytes(const std::vector<uint8_t> & v)
{
    idx_ = 1;
    value_ = v;
}

inline std::vector<r508> partitions::get_array() const
{
    if (idx_ != 1)
    {
        throw avro::Exception("Invalid type for union partitions");
    }
    return std::any_cast<std::vector<r508>>(value_);
}

inline void partitions::set_array(const std::vector<r508> & v)
{
    idx_ = 1;
    value_ = v;
}

inline std::vector<uint8_t> key_metadata::get_bytes() const
{
    if (idx_ != 1)
    {
        throw avro::Exception("Invalid type for union key_metadata");
    }
    return std::any_cast<std::vector<uint8_t>>(value_);
}

inline void key_metadata::set_bytes(const std::vector<uint8_t> & v)
{
    idx_ = 1;
    value_ = v;
}

inline r508_contains_nan::r508_contains_nan() : idx_(0)
{
}
inline r508_lower_bound::r508_lower_bound() : idx_(0)
{
}
inline r508_upper_bound::r508_upper_bound() : idx_(0)
{
}
inline partitions::partitions() : idx_(0)
{
}
inline key_metadata::key_metadata() : idx_(0)
{
}
}
namespace avro
{
template <>
struct codec_traits<Apache::Iceberg::r508_contains_nan>
{
    static void encode(Encoder & e, Apache::Iceberg::r508_contains_nan v)
    {
        e.encodeUnionIndex(v.idx());
        switch (v.idx())
        {
            case 0:
                e.encodeNull();
                break;
            case 1:
                avro::encode(e, v.get_bool());
                break;
        }
    }
    static void decode(Decoder & d, Apache::Iceberg::r508_contains_nan & v)
    {
        size_t n = d.decodeUnionIndex();
        if (n >= 2)
        {
            throw avro::Exception("Union index too big");
        }
        switch (n)
        {
            case 0:
                d.decodeNull();
                v.set_null();
                break;
            case 1:
            {
                bool vv;
                avro::decode(d, vv);
                v.set_bool(vv);
            }
            break;
        }
    }
};

template <>
struct codec_traits<Apache::Iceberg::r508_lower_bound>
{
    static void encode(Encoder & e, Apache::Iceberg::r508_lower_bound v)
    {
        e.encodeUnionIndex(v.idx());
        switch (v.idx())
        {
            case 0:
                e.encodeNull();
                break;
            case 1:
                avro::encode(e, v.get_bytes());
                break;
        }
    }
    static void decode(Decoder & d, Apache::Iceberg::r508_lower_bound & v)
    {
        size_t n = d.decodeUnionIndex();
        if (n >= 2)
        {
            throw avro::Exception("Union index too big");
        }
        switch (n)
        {
            case 0:
                d.decodeNull();
                v.set_null();
                break;
            case 1:
            {
                std::vector<uint8_t> vv;
                avro::decode(d, vv);
                v.set_bytes(vv);
            }
            break;
        }
    }
};

template <>
struct codec_traits<Apache::Iceberg::r508_upper_bound>
{
    static void encode(Encoder & e, Apache::Iceberg::r508_upper_bound v)
    {
        e.encodeUnionIndex(v.idx());
        switch (v.idx())
        {
            case 0:
                e.encodeNull();
                break;
            case 1:
                avro::encode(e, v.get_bytes());
                break;
        }
    }
    static void decode(Decoder & d, Apache::Iceberg::r508_upper_bound & v)
    {
        size_t n = d.decodeUnionIndex();
        if (n >= 2)
        {
            throw avro::Exception("Union index too big");
        }
        switch (n)
        {
            case 0:
                d.decodeNull();
                v.set_null();
                break;
            case 1:
            {
                std::vector<uint8_t> vv;
                avro::decode(d, vv);
                v.set_bytes(vv);
            }
            break;
        }
    }
};

template <>
struct codec_traits<Apache::Iceberg::r508>
{
    static void encode(Encoder & e, const Apache::Iceberg::r508 & v)
    {
        avro::encode(e, v.contains_null);
        avro::encode(e, v.contains_nan);
        avro::encode(e, v.lower_bound);
        avro::encode(e, v.upper_bound);
    }
    static void decode(Decoder & d, Apache::Iceberg::r508 & v)
    {
        if (avro::ResolvingDecoder * rd = dynamic_cast<avro::ResolvingDecoder *>(&d))
        {
            const std::vector<size_t> fo = rd->fieldOrder();
            for (auto it : fo)
            {
                switch (it)
                {
                    case 0:
                        avro::decode(d, v.contains_null);
                        break;
                    case 1:
                        avro::decode(d, v.contains_nan);
                        break;
                    case 2:
                        avro::decode(d, v.lower_bound);
                        break;
                    case 3:
                        avro::decode(d, v.upper_bound);
                        break;
                    default:
                        break;
                }
            }
        }
        else
        {
            avro::decode(d, v.contains_null);
            avro::decode(d, v.contains_nan);
            avro::decode(d, v.lower_bound);
            avro::decode(d, v.upper_bound);
        }
    }
};

template <>
struct codec_traits<Apache::Iceberg::partitions>
{
    static void encode(Encoder & e, Apache::Iceberg::partitions v)
    {
        e.encodeUnionIndex(v.idx());
        switch (v.idx())
        {
            case 0:
                e.encodeNull();
                break;
            case 1:
                avro::encode(e, v.get_array());
                break;
        }
    }
    static void decode(Decoder & d, Apache::Iceberg::partitions & v)
    {
        size_t n = d.decodeUnionIndex();
        if (n >= 2)
        {
            throw avro::Exception("Union index too big");
        }
        switch (n)
        {
            case 0:
                d.decodeNull();
                v.set_null();
                break;
            case 1:
            {
                std::vector<Apache::Iceberg::r508> vv;
                avro::decode(d, vv);
                v.set_array(vv);
            }
            break;
        }
    }
};

template <>
struct codec_traits<Apache::Iceberg::key_metadata>
{
    static void encode(Encoder & e, Apache::Iceberg::key_metadata v)
    {
        e.encodeUnionIndex(v.idx());
        switch (v.idx())
        {
            case 0:
                e.encodeNull();
                break;
            case 1:
                avro::encode(e, v.get_bytes());
                break;
        }
    }
    static void decode(Decoder & d, Apache::Iceberg::key_metadata & v)
    {
        size_t n = d.decodeUnionIndex();
        if (n >= 2)
        {
            throw avro::Exception("Union index too big");
        }
        switch (n)
        {
            case 0:
                d.decodeNull();
                v.set_null();
                break;
            case 1:
            {
                std::vector<uint8_t> vv;
                avro::decode(d, vv);
                v.set_bytes(vv);
            }
            break;
        }
    }
};

template <>
struct codec_traits<Apache::Iceberg::ManifestList>
{
    static void encode(Encoder & e, const Apache::Iceberg::ManifestList & v)
    {
        avro::encode(e, v.manifest_path);
        avro::encode(e, v.manifest_length);
        avro::encode(e, v.partition_spec_id);
        avro::encode(e, v.content);
        avro::encode(e, v.sequence_number);
        avro::encode(e, v.min_sequence_number);
        avro::encode(e, v.added_snapshot_id);
        avro::encode(e, v.added_files_count);
        avro::encode(e, v.existing_files_count);
        avro::encode(e, v.deleted_files_count);
        avro::encode(e, v.added_rows_count);
        avro::encode(e, v.existing_rows_count);
        avro::encode(e, v.deleted_rows_count);
        avro::encode(e, v.partitions);
        avro::encode(e, v.key_metadata);
    }
    static void decode(Decoder & d, Apache::Iceberg::ManifestList & v)
    {
        if (avro::ResolvingDecoder * rd = dynamic_cast<avro::ResolvingDecoder *>(&d))
        {
            const std::vector<size_t> fo = rd->fieldOrder();
            for (auto it : fo)
            {
                switch (it)
                {
                    case 0:
                        avro::decode(d, v.manifest_path);
                        break;
                    case 1:
                        avro::decode(d, v.manifest_length);
                        break;
                    case 2:
                        avro::decode(d, v.partition_spec_id);
                        break;
                    case 3:
                        avro::decode(d, v.content);
                        break;
                    case 4:
                        avro::decode(d, v.sequence_number);
                        break;
                    case 5:
                        avro::decode(d, v.min_sequence_number);
                        break;
                    case 6:
                        avro::decode(d, v.added_snapshot_id);
                        break;
                    case 7:
                        avro::decode(d, v.added_files_count);
                        break;
                    case 8:
                        avro::decode(d, v.existing_files_count);
                        break;
                    case 9:
                        avro::decode(d, v.deleted_files_count);
                        break;
                    case 10:
                        avro::decode(d, v.added_rows_count);
                        break;
                    case 11:
                        avro::decode(d, v.existing_rows_count);
                        break;
                    case 12:
                        avro::decode(d, v.deleted_rows_count);
                        break;
                    case 13:
                        avro::decode(d, v.partitions);
                        break;
                    case 14:
                        avro::decode(d, v.key_metadata);
                        break;
                    default:
                        break;
                }
            }
        }
        else
        {
            avro::decode(d, v.manifest_path);
            avro::decode(d, v.manifest_length);
            avro::decode(d, v.partition_spec_id);
            avro::decode(d, v.content);
            avro::decode(d, v.sequence_number);
            avro::decode(d, v.min_sequence_number);
            avro::decode(d, v.added_snapshot_id);
            avro::decode(d, v.added_files_count);
            avro::decode(d, v.existing_files_count);
            avro::decode(d, v.deleted_files_count);
            avro::decode(d, v.added_rows_count);
            avro::decode(d, v.existing_rows_count);
            avro::decode(d, v.deleted_rows_count);
            avro::decode(d, v.partitions);
            try
            {
                avro::decode(d, v.key_metadata);
            } catch (const avro::Exception & e)
            {
                /// Some tools do not even put key_metadata in the manifest list file, not even `null`!
                if (!std::string(e.what()).contains("EOF reached"))
                    throw e;
            }
        }
    }
};

}
