-- Tags: not_supported, blocked by minIf function
SET query_mode = 'table';
DROP STREAM IF EXISTS min_if;
create stream min_if (arr array(uint8), str string, int int32);
INSERT INTO min_if(arr, str, int) SELECT empty_array_uint8() AS arr, '' AS str, to_int32(0) AS int FROM system.numbers LIMIT 100000;
INSERT INTO min_if(arr, str, int) SELECT [1] AS arr, '2' AS str, to_int32(3) AS int;
INSERT INTO min_if(arr, str, int) SELECT empty_array_uint8() AS arr, '' AS str, to_int32(0) AS int FROM system.numbers LIMIT 100000;

SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;
SELECT minIf(arr, not_empty(arr)) FROM min_if;

SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;
SELECT minIf(str, not_empty(str)) FROM min_if;

SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;

DROP STREAM min_if;
