select to_date(0);
select to_datetime(0, 'Europe/Moscow');
select to_monday(to_date(0));
select to_monday(to_datetime(0, 'Europe/Moscow'));
select toStartOfWeek(to_date(0));
select toStartOfWeek(to_datetime(0, 'Europe/Moscow'));
select to_start_of_month(to_date(0));
select to_start_of_month(to_datetime(0, 'Europe/Moscow'));
select to_start_of_quarter(to_date(0));
select to_start_of_quarter(to_datetime(0, 'Europe/Moscow'));
select to_start_of_year(to_date(0));
select to_start_of_year(to_datetime(0, 'Europe/Moscow'));
select to_time(to_datetime(0, 'Europe/Moscow'));
select to_start_of_minute(to_datetime(0, 'Europe/Moscow'));
select to_start_of_five_minute(to_datetime(0, 'Europe/Moscow'));
select to_start_of_ten_minute(to_datetime(0, 'Europe/Moscow'));
select to_start_of_fifteen_minute(to_datetime(0, 'Europe/Moscow'));
select to_start_of_hour(to_datetime(0, 'Europe/Moscow'));

select to_datetime(0, 'America/Los_Angeles');
select to_monday(to_datetime(0, 'America/Los_Angeles'));
select toStartOfWeek(to_datetime(0, 'America/Los_Angeles'));
select to_start_of_month(to_datetime(0, 'America/Los_Angeles'));
select to_start_of_quarter(to_datetime(0, 'America/Los_Angeles'));
select to_start_of_year(to_datetime(0, 'America/Los_Angeles'));
select to_time(to_datetime(0, 'America/Los_Angeles'), 'America/Los_Angeles');
select to_start_of_minute(to_datetime(0, 'America/Los_Angeles'));
select to_start_of_five_minute(to_datetime(0, 'America/Los_Angeles'));
select to_start_of_ten_minute(to_datetime(0, 'America/Los_Angeles'));
select to_start_of_fifteen_minute(to_datetime(0, 'America/Los_Angeles'));
select to_start_of_hour(to_datetime(0, 'America/Los_Angeles'));
