#!/bin/bash

#Release, RelWithDebInfo, Debug
build_type="$1"
sanitizer="$2" # address
build_type="${build_type:=Release}"
sanitizer="${sanitizer}"

cmake .. \
    -DCMAKE_BUILD_TYPE=${build_type} \
    -DENABLE_PROTON_ALL=OFF \
    -DENABLE_PROTON_SERVER=ON \
    -DENABLE_PROTON_CLIENT=ON \
    -DENABLE_PROTON_KLOG_BENCHMARK=ON \
    -DENABLE_PROTON_INSTALL=ON \
    -DENABLE_PROTON_METASTORE=ON \
    -DUSE_STATIC_LIBRARIES=ON \
    -DUSE_UNWIND=ON \
    -DUSE_DEBUG_HELPERS=ON \
    -DENABLE_LIBRARIES=OFF \
    -DENABLE_KAFKA=ON \
    -DENABLE_NURAFT=ON \
    -DENABLE_RAPIDJSON=ON \
    -DENABLE_YAML_CPP=ON \
    -DENABLE_SIMDJSON=ON \
    -DENABLE_ROCKSDB=ON \
    -DENABLE_REPLXX=ON \
    -DENABLE_JEMALLOC=OFF \
    -DENABLE_SSL=ON \
    -DENABLE_BZIP2=ON \
    -DENABLE_PROTOBUF=ON \
    -DENABLE_URING=ON \
    -DENABLE_UTILS=ON \
    -DENABLE_THINLTO=OFF \
    -DENABLE_CLANG_TIDY=OFF \
    -DENABLE_TESTS=ON \
    -DENABLE_EXAMPLES=ON \
    -DSTRIP_DEBUG_SYMBOLS_FUNCTIONS=ON \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DENABLE_CCACHE=ON \
    -DENABLE_CHECK_HEAVY_BUILDS=1 \
    -DENABLE_GRPC=ON \
    -DENABLE_MATH_FUNCS=ON \
    -DENABLE_GEO_FUNCS=ON \
    -DENABLE_HIGH_ORDER_ARRAY_FUNCS=ON \
    -DENABLE_PARQUET=ON \
    -DENABLE_THRIFT=ON \
    -DENABLE_CYRUS_SASL=ON \
    -DENABLE_KRB5=ON \
    -DSANITIZE=${sanitizer}

