#!/bin/bash

#Release, RelWithDebInfo, Debug
build_type="$1"
build_type="${build_type:=Release}"

sanitizer=""
if [ "$build_type" = "Debug" ]; then
    sanitizer="address"
fi

enable_jemalloc="OFF"
if [ -z "$sanitizer" ]; then
    enable_jemalloc="ON"
fi

cmake .. \
    -DCMAKE_BUILD_TYPE="$build_type" \
    -DENABLE_PROTON_ALL=OFF \
    -DENABLE_PROTON_SERVER=ON \
    -DENABLE_PROTON_CLIENT=ON \
    -DENABLE_PROTON_KLOG_BENCHMARK=ON \
    -DENABLE_PROTON_INSTALL=ON \
    -DENABLE_PROTON_METASTORE=ON \
    -DUSE_DEBUG_HELPERS=ON \
    -DENABLE_LIBRARIES=OFF \
    -DENABLE_BENCHMARKS=ON \
    -DENABLE_KAFKA=ON \
    -DENABLE_NURAFT=ON \
    -DENABLE_RAPIDJSON=ON \
    -DENABLE_YAML_CPP=ON \
    -DENABLE_SIMDJSON=ON \
    -DENABLE_ROCKSDB=ON \
    -DENABLE_JEMALLOC=${enable_jemalloc} \
    -DENABLE_SSL=ON \
    -DENABLE_BZIP2=ON \
    -DENABLE_BROTLI=ON \
    -DENABLE_PROTOBUF=ON \
    -DENABLE_LIBURING=ON \
    -DENABLE_UTILS=ON \
    -DENABLE_THINLTO=OFF \
    -DENABLE_CLANG_TIDY=OFF \
    -DENABLE_TESTS=ON \
    -DENABLE_EXAMPLES=ON \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DENABLE_CCACHE=ON \
    -DENABLE_CHECK_HEAVY_BUILDS=1 \
    -DENABLE_GRPC=ON \
    -DENABLE_MATH_FUNCS=ON \
    -DENABLE_GEO_FUNCS=ON \
    -DENABLE_HIGH_ORDER_ARRAY_FUNCS=ON \
    -DENABLE_PARQUET=ON \
    -DENABLE_THRIFT=ON \
    -DENABLE_CYRUS_SASL=ON \
    -DENABLE_KRB5=ON \
    -DSANITIZE=${sanitizer} \
    -DENABLE_BITMAP_FUNCS=ON \
    -DENABLE_BINARY_REPR_FUNCS=ON \
    -DENABLE_IP_CODING_FUNCS=ON \
    -DENABLE_UUID_CODING_FUNCS=ON \
    -DENABLE_EXTERNAL_DICT_FUNCS=OFF \
    -DENABLE_FORMATTING_FUNCS=ON \
    -DENABLE_HASH_FUNCS=ON \
    -DENABLE_HIGH_ORDER_ARRAY_FUNCS=ON \
    -DENABLE_MISC_FUNCS=ON \
    -DENABLE_MATH_FUNCS=ON \
    -DENABLE_GEO_FUNCS=ON \
    -DENABLE_H3_GEO_FUNCS=ON \
    -DENABLE_S2_GEO_FUNCS=ON \
    -DENABLE_INTROSPECTION_FUNCS=ON \
    -DUSE_CONSISTENT_HASH_FUNCS=ON \
    -DENABLE_HAMMING_DISTANCE_FUNCS=ON \
    -DENABLE_SNOWFLAKE_FUNCS=ON \
    -DENABLE_ENCRYPT_DECRYPT_FUNCS=ON \
    -DENABLE_DEBUG_FUNCS=ON \
    -DENABLE_URL_FUNCS=ON \
    -DENABLE_AVRO=ON

