#!/bin/bash

#Release, RelWithDebInfo, Debug
build_type="$1"
build_type="${build_type:=Release}"

cmake .. \
    -DCMAKE_BUILD_TYPE=${build_type} \
    -DENABLE_PROTON_ALL=OFF \
    -DENABLE_PROTON_SERVER=ON \
    -DENABLE_PROTON_CLIENT=ON \
    -DENABLE_PROTON_KLOG_BENCHMARK=ON \
    -DENABLE_PROTON_INSTALL=ON \
    -DENABLE_PROTON_METASTORE=ON \
    -DUSE_STATIC_LIBRARIES=ON \
    -DUSE_UNWIND=ON \
    -DUSE_DEBUG_HELPERS=ON \
    -DENABLE_LIBRARIES=OFF \
    -DENABLE_KAFKA=ON \
    -DENABLE_NURAFT=ON \
    -DENABLE_RAPIDJSON=ON \
    -DENABLE_YAML_CPP=ON \
    -DENABLE_NURAFT=ON \
    -DENABLE_SIMDJSON=ON \
    -DENABLE_ROCKSDB=ON \
    -DENABLE_REPLXX=ON \
    -DENABLE_JEMALLOC=OFF \
    -DENABLE_SSL=ON \
    -DENABLE_BZIP2=OFF \
    -DENABLE_PROTOBUF=ON \
    -DENABLE_URING=ON \
    -DENABLE_UTILS=OFF \
    -DENABLE_THINLTO=OFF \
    -DENABLE_CLANG_TIDY=OFF \
    -DENABLE_TESTS=ON \
    -DSTRIP_DEBUG_SYMBOLS_FUNCTIONS=ON \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DSANITIZE=address \
    -DENABLE_CCACHE=ON

