SELECT '---map--';
SELECT array_map(x -> 123, empty_array_uint8());
SELECT array_map(x -> 123, [1, 2, 3]);
SELECT array_map(x -> 123, range(number)) FROM system.numbers LIMIT 10;
SELECT '---filter--';
SELECT array_filter(x -> 0, empty_array_uint8());
SELECT array_filter(x -> 0, [1, 2, 3]);
SELECT array_filter(x -> 0, range(number)) FROM system.numbers LIMIT 10;
SELECT array_filter(x -> 1, empty_array_uint8());
SELECT array_filter(x -> 1, [1, 2, 3]);
SELECT array_filter(x -> 1, range(number)) FROM system.numbers LIMIT 10;
SELECT '---count---';
SELECT arrayCount(x -> 0, empty_array_uint8());
SELECT arrayCount(x -> 0, [1, 2, 3]);
SELECT arrayCount(x -> 0, range(number)) FROM system.numbers LIMIT 10;
SELECT arrayCount(x -> 1, empty_array_uint8());
SELECT arrayCount(x -> 1, [1, 2, 3]);
SELECT arrayCount(x -> 1, range(number)) FROM system.numbers LIMIT 10;
SELECT '---sum---';
SELECT arraySum(x -> 0, empty_array_uint8());
SELECT arraySum(x -> 0, [1, 2, 3]);
SELECT arraySum(x -> 0, range(number)) FROM system.numbers LIMIT 10;
SELECT arraySum(x -> 10, empty_array_uint8());
SELECT arraySum(x -> 10, [1, 2, 3]);
SELECT arraySum(x -> 10, range(number)) FROM system.numbers LIMIT 10;
SELECT '---all---';
SELECT arrayAll(x -> 0, empty_array_uint8());
SELECT arrayAll(x -> 0, [1, 2, 3]);
SELECT arrayAll(x -> 0, range(number)) FROM system.numbers LIMIT 10;
SELECT arrayAll(x -> 1, empty_array_uint8());
SELECT arrayAll(x -> 1, [1, 2, 3]);
SELECT arrayAll(x -> 1, range(number)) FROM system.numbers LIMIT 10;
SELECT '---exists---';
SELECT array_exists(x -> 0, empty_array_uint8());
SELECT array_exists(x -> 0, [1, 2, 3]);
SELECT array_exists(x -> 0, range(number)) FROM system.numbers LIMIT 10;
SELECT array_exists(x -> 1, empty_array_uint8());
SELECT array_exists(x -> 1, [1, 2, 3]);
SELECT array_exists(x -> 1, range(number)) FROM system.numbers LIMIT 10;
SELECT '---first---';
SELECT arrayFirst(x -> 0, empty_array_uint8());
SELECT arrayFirst(x -> 0, [1, 2, 3]);
SELECT arrayFirst(x -> 0, range(number)) FROM system.numbers LIMIT 10;
SELECT arrayFirst(x -> 1, empty_array_uint8());
SELECT arrayFirst(x -> 1, [1, 2, 3]);
SELECT arrayFirst(x -> 1, range(number)) FROM system.numbers LIMIT 10;
SELECT '---first index---';
SELECT arrayFirstIndex(x -> 0, empty_array_uint8());
SELECT arrayFirstIndex(x -> 0, [1, 2, 3]);
SELECT arrayFirstIndex(x -> 0, range(number)) FROM system.numbers LIMIT 10;
SELECT arrayFirstIndex(x -> 1, empty_array_uint8());
SELECT arrayFirstIndex(x -> 1, [1, 2, 3]);
SELECT arrayFirstIndex(x -> 1, range(number)) FROM system.numbers LIMIT 10;
SELECT '---cumsum---';
SELECT arrayCumSum(x -> 0, empty_array_uint8());
SELECT arrayCumSum(x -> 0, [1, 2, 3]);
SELECT arrayCumSum(x -> 0, range(number)) FROM system.numbers LIMIT 10;
SELECT arrayCumSum(x -> 10, empty_array_uint8());
SELECT arrayCumSum(x -> 10, [1, 2, 3]);
SELECT arrayCumSum(x -> 10, range(number)) FROM system.numbers LIMIT 10;

SELECT '---map--';
SELECT array_map(x -> materialize(123), empty_array_uint8());
SELECT array_map(x -> materialize(123), [1, 2, 3]);
SELECT array_map(x -> materialize(123), range(number)) FROM system.numbers LIMIT 10;
SELECT '---filter--';
SELECT array_filter(x -> materialize(0), empty_array_uint8());
SELECT array_filter(x -> materialize(0), [1, 2, 3]);
SELECT array_filter(x -> materialize(0), range(number)) FROM system.numbers LIMIT 10;
SELECT array_filter(x -> materialize(1), empty_array_uint8());
SELECT array_filter(x -> materialize(1), [1, 2, 3]);
SELECT array_filter(x -> materialize(1), range(number)) FROM system.numbers LIMIT 10;
SELECT '---count---';
SELECT arrayCount(x -> materialize(0), empty_array_uint8());
SELECT arrayCount(x -> materialize(0), [1, 2, 3]);
SELECT arrayCount(x -> materialize(0), range(number)) FROM system.numbers LIMIT 10;
SELECT arrayCount(x -> materialize(1), empty_array_uint8());
SELECT arrayCount(x -> materialize(1), [1, 2, 3]);
SELECT arrayCount(x -> materialize(1), range(number)) FROM system.numbers LIMIT 10;
SELECT '---sum---';
SELECT arraySum(x -> materialize(0), empty_array_uint8());
SELECT arraySum(x -> materialize(0), [1, 2, 3]);
SELECT arraySum(x -> materialize(0), range(number)) FROM system.numbers LIMIT 10;
SELECT arraySum(x -> materialize(10), empty_array_uint8());
SELECT arraySum(x -> materialize(10), [1, 2, 3]);
SELECT arraySum(x -> materialize(10), range(number)) FROM system.numbers LIMIT 10;
SELECT '---all---';
SELECT arrayAll(x -> materialize(0), empty_array_uint8());
SELECT arrayAll(x -> materialize(0), [1, 2, 3]);
SELECT arrayAll(x -> materialize(0), range(number)) FROM system.numbers LIMIT 10;
SELECT arrayAll(x -> materialize(1), empty_array_uint8());
SELECT arrayAll(x -> materialize(1), [1, 2, 3]);
SELECT arrayAll(x -> materialize(1), range(number)) FROM system.numbers LIMIT 10;
SELECT '---exists---';
SELECT array_exists(x -> materialize(0), empty_array_uint8());
SELECT array_exists(x -> materialize(0), [1, 2, 3]);
SELECT array_exists(x -> materialize(0), range(number)) FROM system.numbers LIMIT 10;
SELECT array_exists(x -> materialize(1), empty_array_uint8());
SELECT array_exists(x -> materialize(1), [1, 2, 3]);
SELECT array_exists(x -> materialize(1), range(number)) FROM system.numbers LIMIT 10;
SELECT '---first---';
SELECT arrayFirst(x -> materialize(0), empty_array_uint8());
SELECT arrayFirst(x -> materialize(0), [1, 2, 3]);
SELECT arrayFirst(x -> materialize(0), range(number)) FROM system.numbers LIMIT 10;
SELECT arrayFirst(x -> materialize(1), empty_array_uint8());
SELECT arrayFirst(x -> materialize(1), [1, 2, 3]);
SELECT arrayFirst(x -> materialize(1), range(number)) FROM system.numbers LIMIT 10;
SELECT '---first index---';
SELECT arrayFirstIndex(x -> materialize(0), empty_array_uint8());
SELECT arrayFirstIndex(x -> materialize(0), [1, 2, 3]);
SELECT arrayFirstIndex(x -> materialize(0), range(number)) FROM system.numbers LIMIT 10;
SELECT arrayFirstIndex(x -> materialize(1), empty_array_uint8());
SELECT arrayFirstIndex(x -> materialize(1), [1, 2, 3]);
SELECT arrayFirstIndex(x -> materialize(1), range(number)) FROM system.numbers LIMIT 10;
SELECT '--cumsum---';
SELECT arrayCumSum(x -> materialize(0), empty_array_uint8());
SELECT arrayCumSum(x -> materialize(0), [1, 2, 3]);
SELECT arrayCumSum(x -> materialize(0), range(number)) FROM system.numbers LIMIT 10;
SELECT arrayCumSum(x -> materialize(10), empty_array_uint8());
SELECT arrayCumSum(x -> materialize(10), [1, 2, 3]);
SELECT arrayCumSum(x -> materialize(10), range(number)) FROM system.numbers LIMIT 10;

SELECT '---map--';
SELECT array_map(x -> 123, empty_array_string());
SELECT array_map(x -> 123, array_map(x -> to_string(x), [1, 2, 3]));
SELECT array_map(x -> 123, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT '---filter--';
SELECT array_filter(x -> 0, empty_array_string());
SELECT array_filter(x -> 0, array_map(x -> to_string(x), [1, 2, 3]));
SELECT array_filter(x -> 0, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT array_filter(x -> 1, empty_array_string());
SELECT array_filter(x -> 1, array_map(x -> to_string(x), [1, 2, 3]));
SELECT array_filter(x -> 1, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT '---count---';
SELECT arrayCount(x -> 0, empty_array_string());
SELECT arrayCount(x -> 0, array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayCount(x -> 0, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT arrayCount(x -> 1, empty_array_string());
SELECT arrayCount(x -> 1, array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayCount(x -> 1, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT '---sum---';
SELECT arraySum(x -> 0, empty_array_string());
SELECT arraySum(x -> 0, array_map(x -> to_string(x), [1, 2, 3]));
SELECT arraySum(x -> 0, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT arraySum(x -> 10, empty_array_string());
SELECT arraySum(x -> 10, array_map(x -> to_string(x), [1, 2, 3]));
SELECT arraySum(x -> 10, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT '---all---';
SELECT arrayAll(x -> 0, empty_array_string());
SELECT arrayAll(x -> 0, array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayAll(x -> 0, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT arrayAll(x -> 1, empty_array_string());
SELECT arrayAll(x -> 1, array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayAll(x -> 1, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT '---exists---';
SELECT array_exists(x -> 0, empty_array_string());
SELECT array_exists(x -> 0, array_map(x -> to_string(x), [1, 2, 3]));
SELECT array_exists(x -> 0, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT array_exists(x -> 1, empty_array_string());
SELECT array_exists(x -> 1, array_map(x -> to_string(x), [1, 2, 3]));
SELECT array_exists(x -> 1, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT '---first---';
SELECT arrayFirst(x -> 0, empty_array_string());
SELECT arrayFirst(x -> 0, array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayFirst(x -> 0, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT arrayFirst(x -> 1, empty_array_string());
SELECT arrayFirst(x -> 1, array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayFirst(x -> 1, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT '---first index---';
SELECT arrayFirstIndex(x -> 0, empty_array_string());
SELECT arrayFirstIndex(x -> 0, array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayFirstIndex(x -> 0, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT arrayFirstIndex(x -> 1, empty_array_string());
SELECT arrayFirstIndex(x -> 1, array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayFirstIndex(x -> 1, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT '---cumsum---';
SELECT arrayCumSum(x -> 0, empty_array_string());
SELECT arrayCumSum(x -> 0, array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayCumSum(x -> 0, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT arrayCumSum(x -> 10, empty_array_string());
SELECT arrayCumSum(x -> 10, array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayCumSum(x -> 10, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;

SELECT '---map--';
SELECT array_map(x -> materialize(123), empty_array_string());
SELECT array_map(x -> materialize(123), array_map(x -> to_string(x), [1, 2, 3]));
SELECT array_map(x -> materialize(123), array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT '---filter--';
SELECT array_filter(x -> materialize(0), empty_array_string());
SELECT array_filter(x -> materialize(0), array_map(x -> to_string(x), [1, 2, 3]));
SELECT array_filter(x -> materialize(0), array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT array_filter(x -> materialize(1), empty_array_string());
SELECT array_filter(x -> materialize(1), array_map(x -> to_string(x), [1, 2, 3]));
SELECT array_filter(x -> materialize(1), array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT '---count---';
SELECT arrayCount(x -> materialize(0), empty_array_string());
SELECT arrayCount(x -> materialize(0), array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayCount(x -> materialize(0), array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT arrayCount(x -> materialize(1), empty_array_string());
SELECT arrayCount(x -> materialize(1), array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayCount(x -> materialize(1), array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT '---sum---';
SELECT arraySum(x -> materialize(0), empty_array_string());
SELECT arraySum(x -> materialize(0), array_map(x -> to_string(x), [1, 2, 3]));
SELECT arraySum(x -> materialize(0), array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT arraySum(x -> materialize(10), empty_array_string());
SELECT arraySum(x -> materialize(10), array_map(x -> to_string(x), [1, 2, 3]));
SELECT arraySum(x -> materialize(10), array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT '---all---';
SELECT arrayAll(x -> materialize(0), empty_array_string());
SELECT arrayAll(x -> materialize(0), array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayAll(x -> materialize(0), array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT arrayAll(x -> materialize(1), empty_array_string());
SELECT arrayAll(x -> materialize(1), array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayAll(x -> materialize(1), array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT '---exists---';
SELECT array_exists(x -> materialize(0), empty_array_string());
SELECT array_exists(x -> materialize(0), array_map(x -> to_string(x), [1, 2, 3]));
SELECT array_exists(x -> materialize(0), array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT array_exists(x -> materialize(1), empty_array_string());
SELECT array_exists(x -> materialize(1), array_map(x -> to_string(x), [1, 2, 3]));
SELECT array_exists(x -> materialize(1), array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT '---first---';
SELECT arrayFirst(x -> materialize(0), empty_array_string());
SELECT arrayFirst(x -> materialize(0), array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayFirst(x -> materialize(0), array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT arrayFirst(x -> materialize(1), empty_array_string());
SELECT arrayFirst(x -> materialize(1), array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayFirst(x -> materialize(1), array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT '---first index---';
SELECT arrayFirstIndex(x -> materialize(0), empty_array_string());
SELECT arrayFirstIndex(x -> materialize(0), array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayFirstIndex(x -> materialize(0), array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT arrayFirstIndex(x -> materialize(1), empty_array_string());
SELECT arrayFirstIndex(x -> materialize(1), array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayFirstIndex(x -> materialize(1), array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT '---cumsum---';
SELECT arrayCumSum(x -> materialize(0), empty_array_string());
SELECT arrayCumSum(x -> materialize(0), array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayCumSum(x -> materialize(0), array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT arrayCumSum(x -> materialize(10), empty_array_string());
SELECT arrayCumSum(x -> materialize(10), array_map(x -> to_string(x), [1, 2, 3]));
SELECT arrayCumSum(x -> materialize(10), array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;

SELECT '--- ---';
SELECT array_map(x -> number % 2, range(number)) FROM system.numbers LIMIT 10;
SELECT array_filter(x -> number % 2, range(number)) FROM system.numbers LIMIT 10;
SELECT arrayCount(x -> number % 2, range(number)) FROM system.numbers LIMIT 10;
SELECT arraySum(x -> number % 2, range(number)) FROM system.numbers LIMIT 10;
SELECT arrayAll(x -> number % 2, range(number)) FROM system.numbers LIMIT 10;
SELECT array_exists(x -> number % 2, range(number)) FROM system.numbers LIMIT 10;
SELECT arrayFirst(x -> number % 2, range(number)) FROM system.numbers LIMIT 10;
SELECT arrayFirstIndex(x -> number % 2, range(number)) FROM system.numbers LIMIT 10;
SELECT arrayCumSum(x -> number % 2, range(number)) FROM system.numbers LIMIT 10;
SELECT '--- ---';
SELECT array_map(x -> number % 2, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT array_filter(x -> number % 2, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT arrayCount(x -> number % 2, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT arraySum(x -> number % 2, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT arrayAll(x -> number % 2, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT array_exists(x -> number % 2, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT arrayFirst(x -> number % 2, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT arrayFirstIndex(x -> number % 2, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
SELECT arrayCumSum(x -> number % 2, array_map(x -> to_string(x), range(number))) FROM system.numbers LIMIT 10;
