DROP TEMPORARY STREAM IF EXISTS temp_tab;
CREATE TEMPORARY STREAM temp_tab (number uint64);
EXISTS TEMPORARY TABLE temp_tab;
SHOW CREATE TEMPORARY STREAM temp_tab;
SHOW TEMPORARY TABLES LIKE 'temp_tab';
DROP TEMPORARY TABLE temp_tab;
EXISTS TEMPORARY TABLE temp_tab;