DROP STREAM IF EXISTS t;
CREATE STREAM t (x decimal(18, 3)) ENGINE = MergeTree ORDER BY x;
INSERT INTO t VALUES (1.1);
SELECT * FROM t WHERE to_uint64(x) = 1;
DROP STREAM t;

CREATE STREAM t (x DateTime64(3)) ENGINE = MergeTree ORDER BY x;
INSERT INTO t VALUES (1000);
SELECT x::uint64 FROM t WHERE to_uint64(x) = 1;
DROP STREAM t;
