services:
  proton:
    image: ghcr.io/timeplus-io/proton:latest
    pull_policy: always
  hackernews_bytewax:
    image: timeplus/hackernews_bytewax:latest
    environment:
      - PROTON_HOST=proton
    depends_on:
      - proton
