#include <Processors/Formats/Impl/ProtobufRowInputFormat.h>

#if USE_PROTOBUF
#   include <Core/Block.h>
#   include <Formats/FormatFactory.h>
#   include <Formats/ProtobufReader.h>
#   include <Formats/ProtobufSchemas.h>
#   include <Formats/ProtobufSerializer.h>
#   include <IO/WriteBufferFromFile.h>

/// proton: starts
#   include <Common/LRUCache.h>
#   include <Formats/KafkaSchemaRegistry.h>
#   include <IO/VarInt.h>
#   include <span>

#   include <google/protobuf/compiler/parser.h>
#   include <google/protobuf/descriptor.pb.h>
#   include <google/protobuf/io/tokenizer.h>

#   include <Common/re2.h>
/// proton: ends

namespace DB
{

/// proton: starts
namespace ErrorCodes
{
extern const int INVALID_DATA;
extern const int INVALID_SETTING_VALUE;
}
/// proton: ends

ProtobufRowInputFormat::ProtobufRowInputFormat(
    ReadBuffer & in_,
    const Block & header_,
    const Params & params_,
    const ProtobufSchemaInfo & schema_info_,
    bool with_length_delimiter_,
    bool flatten_google_wrappers_,
    const String & google_protos_path)
    : IRowInputFormat(header_, in_, params_, ProcessorID::ProtobufRowInputFormatID)
    , descriptor(ProtobufSchemas::instance().getMessageTypeForFormatSchema(
          schema_info_.getSchemaInfo(), ProtobufSchemas::WithEnvelope::No, google_protos_path))
    , with_length_delimiter(with_length_delimiter_)
    , flatten_google_wrappers(flatten_google_wrappers_)
{
}

void ProtobufRowInputFormat::createReaderAndSerializer()
{
    reader = std::make_unique<ProtobufReader>(*in);
    serializer = ProtobufSerializer::create(
        getPort().getHeader().getNames(),
        getPort().getHeader().getDataTypes(),
        missing_column_indices,
        descriptor,
        with_length_delimiter,
        /* with_envelope = */ false,
        flatten_google_wrappers,
        *reader);
}

void ProtobufRowInputFormat::destroyReaderAndSerializer()
{
    serializer = nullptr;
    reader.reset();
}

bool ProtobufRowInputFormat::readRow(MutableColumns & columns, RowReadExtension & row_read_extension)
try
{
    if (!reader)
        createReaderAndSerializer();

    if (reader->eof())
        return false;

    size_t row_num = columns.empty() ? 0 : columns[0]->size();
    if (row_num == 0u)
        serializer->setColumns(columns.data(), columns.size());

    serializer->readRow(row_num);

    row_read_extension.read_columns.clear();
    row_read_extension.read_columns.resize(columns.size(), true);
    for (size_t column_idx : missing_column_indices)
        row_read_extension.read_columns[column_idx] = false;
    return true;
}
catch (...)
{
    destroyReaderAndSerializer();
    throw;
}

void ProtobufRowInputFormat::setReadBuffer(ReadBuffer & in_)
{
    if (reader)
        reader->setReadBuffer(in_);
    IRowInputFormat::setReadBuffer(in_);
}

bool ProtobufRowInputFormat::allowSyncAfterError() const
{
    return true;
}

void ProtobufRowInputFormat::syncAfterError()
{
    reader->endMessage(true);
}

size_t ProtobufRowInputFormat::countRows(size_t max_block_size)
try
{
    if (!reader)
        createReaderAndSerializer();

    size_t num_rows = 0;
    while (!reader->eof() && num_rows < max_block_size)
    {
        reader->startMessage(with_length_delimiter);
        reader->endMessage(false);
        ++num_rows;
    }

    return num_rows;
}
catch (...)
{
    destroyReaderAndSerializer();
    throw;
}

void registerInputFormatProtobuf(FormatFactory & factory)
{
    /// proton: starts
    factory.registerInputFormat(
        "ProtobufSingle",
        [](ReadBuffer & buf, const Block & sample, IRowInputFormat::Params params, const FormatSettings & settings)
            -> std::shared_ptr<IInputFormat>
        {
            if (settings.kafka_schema_registry.url.empty())
                return std::make_shared<ProtobufRowInputFormat>(
                    buf,
                    sample,
                    std::move(params),
                    ProtobufSchemaInfo(settings, "Protobuf", sample, settings.protobuf.use_autogenerated_schema),
                    /*with_length_delimiter=*/false,
                    settings.protobuf.input_flatten_google_wrappers,
                    settings.protobuf.google_protos_path);

            if (!settings.schema.format_schema.empty())
                throw Exception(
                    ErrorCodes::INVALID_SETTING_VALUE, "kafka_schema_registry_url and format_schema cannot be used at the same time");

            return std::make_shared<ProtobufConfluentRowInputFormat>(buf, sample, std::move(params), settings);
        });
    factory.markFormatSupportsSubsetOfColumns("ProtobufSingle");

    factory.registerInputFormat(
        "Protobuf", [](ReadBuffer & buf, const Block & sample, IRowInputFormat::Params params, const FormatSettings & settings)
        {
            return std::make_shared<ProtobufRowInputFormat>(
                buf,
                sample,
                std::move(params),
                ProtobufSchemaInfo(settings, "Protobuf", sample, settings.protobuf.use_autogenerated_schema),
                /*with_length_delimiter=*/true,
                settings.protobuf.input_flatten_google_wrappers,
                settings.protobuf.google_protos_path);
        });
    factory.markFormatSupportsSubsetOfColumns("Protobuf");
    /// proton: ends
}

ProtobufSchemaReader::ProtobufSchemaReader(const FormatSettings & format_settings)
    : schema_info(
          format_settings.schema.format_schema,
          "Protobuf",
          true,
          format_settings.schema.is_server, format_settings.schema.format_schema_path)
    , skip_unsupported_fields(format_settings.protobuf.skip_fields_with_unsupported_types_in_schema_inference)
    , google_protos_path(format_settings.protobuf.google_protos_path)
{
}

NamesAndTypesList ProtobufSchemaReader::readSchema()
{
    auto descriptor = ProtobufSchemas::instance().getMessageTypeForFormatSchema(
        schema_info, ProtobufSchemas::WithEnvelope::No, google_protos_path);
    return protobufSchemaToCHSchema(descriptor.message_descriptor, skip_unsupported_fields);
}

/// proton: starts
namespace
{
using ConfluentSchemaRegistry = ProtobufConfluentRowInputFormat::SchemaRegistryWithCache;

auto & schemaRegistryCache()
{
    static LRUCache<KafkaSchemaRegistry::CacheKey, ConfluentSchemaRegistry, KafkaSchemaRegistry::CacheHasher> schema_registry_cache(/*max_size_=*/1000);
    return schema_registry_cache;
}

std::shared_ptr<ConfluentSchemaRegistry> getConfluentSchemaRegistry(const FormatSettings & format_settings)
{
    KafkaSchemaRegistry::CacheKey key {
          format_settings.kafka_schema_registry.url,
          format_settings.kafka_schema_registry.credentials,
          format_settings.kafka_schema_registry.private_key_file,
          format_settings.kafka_schema_registry.certificate_file,
          format_settings.kafka_schema_registry.ca_location,
          format_settings.kafka_schema_registry.skip_cert_check};

    auto [schema_registry, loaded] = schemaRegistryCache().getOrSet(
        key,
        [&key]() { return std::make_shared<ConfluentSchemaRegistry>(key.base_url, key.credentials, key.private_key_file, key.certificate_file, key.ca_location, key.skip_cert_check); });
    return schema_registry;
}
}

/// Confluent/descriptor-canonicalized protobuf schemas render `map<K,V>` fields in their
/// expanded form: a synthetic nested message carrying `option map_entry = true` plus a
/// `repeated <Entry> field = N;`. The protobuf *source* parser (compiler::Parser) rejects an
/// explicitly-set map_entry option, so such schemas fail to parse even though they are valid
/// descriptors. Collapse them back to `map<K,V>` sugar (keyed on the explicit map_entry marker),
/// which the parser accepts and which builds an identical descriptor.
///
/// This is a no-op when the text contains no `map_entry` option, so schemas that already parse
/// are returned byte-for-byte unchanged.
String collapseProtobufMapEntries(String schema)
{
    if (schema.find("map_entry") == String::npos) /// fast, safe bail-out for the common case
        return schema;

    /// message <Name> { option map_entry = true; [optional|required] <K> key = 1; [optional|required] <V> value = 2; }
    static const re2::RE2 entry_re(
        R"(message\s+(\w+)\s*\{\s*option\s+map_entry\s*=\s*true\s*;\s*)"
        R"((?:optional\s+|required\s+)?([\w.]+)\s+key\s*=\s*1\s*;\s*)"
        R"((?:optional\s+|required\s+)?([\w.]+)\s+value\s*=\s*2\s*;\s*\})");

    struct MapEntry
    {
        std::string name;
        std::string key;
        std::string value;
    };
    std::vector<MapEntry> entries;
    {
        re2::StringPiece input(schema);
        std::string name;
        std::string key;
        std::string value;
        while (re2::RE2::FindAndConsume(&input, entry_re, &name, &key, &value))
            entries.push_back({name, key, value});
    }

    /// `map_entry` text present but not in the recognized shape: leave it to the strict parser
    /// (which will report the original error) rather than risk an unsound rewrite.
    if (entries.empty())
        return schema;

    re2::RE2::GlobalReplace(&schema, entry_re, ""); /// drop the synthetic entry messages

    for (const auto & entry : entries)
    {
        /// repeated [<qualifier>.]<Name> <field> = <n> [opts]; -> map<K, V> <field> = <n>;
        const re2::RE2 field_re(
            R"(repeated\s+(?:[\w.]+\.)?)" + re2::RE2::QuoteMeta(entry.name)
            + R"(\s+(\w+)\s*=\s*(\d+)\s*(?:\[[^\]]*\])?\s*;)");
        re2::RE2::GlobalReplace(&schema, field_re, "map<" + entry.key + ", " + entry.value + R"(> \1 = \2;)");
    }

    return schema;
}

class ProtobufConfluentRowInputFormat::SchemaRegistryWithCache : public google::protobuf::io::ErrorCollector
{
public:
    SchemaRegistryWithCache(
        const String & base_url,
        const String & credentials,
        const String & private_key_file,
        const String & certificate_file,
        const String & ca_location,
        bool skip_cert_check)
        : registry(base_url, credentials, private_key_file, certificate_file, ca_location, skip_cert_check) { }

    /// Overrides google::protobuf::io::ErrorCollector.
    void AddError(int line, google::protobuf::io::ColumnNumber column, const std::string & message) override
    {
        throw Exception(ErrorCodes::INVALID_DATA, "Failed to parse schema, line={}, column={}, message={}", line, column, message);
    }

    /// Get message type from latest subject schema
    const google::protobuf::Descriptor * getMessageType(const String & subject, bool collapse_map_entry_)
    {
        auto [schema_id, _] = registry.fetchLatestSchemaForSubject(subject);
        const auto * fd = getSchema(schema_id, collapse_map_entry_);
        return fd->message_type(0);
    }

    const google::protobuf::Descriptor * getMessageType(uint32_t schema_id, const std::vector<Int64> & indexes, bool collapse_map_entry_)
    {
        if (indexes.empty())
            throw Exception(ErrorCodes::INVALID_DATA, "Empty message indexes in confluent protobuf wire format");

        const auto * fd = getSchema(schema_id, collapse_map_entry_);

        /// Check https://docs.confluent.io/platform/current/schema-registry/fundamentals/serdes-develop/index.html#wire-format
        /// for how to get the message with the indexes.
        auto mt_count = fd->message_type_count();
        if (indexes[0] < 0 || indexes[0] >= mt_count)
            throw Exception(ErrorCodes::INVALID_DATA, "Invalid message index={} message_type_count={}", indexes[0], mt_count);

        const auto * descriptor = fd->message_type(static_cast<int32_t>(indexes[0]));

        for (int64_t i : std::span(indexes.begin() + 1, indexes.end()))
        {
            auto nested_count = descriptor->nested_type_count();
            if (i < 0 || i >= nested_count)
                throw Exception(
                    ErrorCodes::INVALID_DATA,
                    "Invalid nested message index={} nested_type_count={} descriptor={}",
                    i,
                    nested_count,
                    descriptor->name());
            descriptor = descriptor->nested_type(static_cast<int32_t>(i));
        }

        return descriptor;
    }

private:
    const google::protobuf::FileDescriptor * getSchema(uint32_t id, bool collapse_map_entry_)
    {
        const auto * loaded_descriptor = descriptor_pool.FindFileByName(std::to_string(id));
        if (loaded_descriptor != nullptr)
            return loaded_descriptor;

        return fetchSchema(id, collapse_map_entry_);
    }

    const google::protobuf::FileDescriptor * fetchSchema(uint32_t id, bool collapse_map_entry_)
    {
        std::lock_guard lock(mutex);
        /// Just in case we got beaten
        const auto * loaded_descriptor = descriptor_pool.FindFileByName(std::to_string(id));
        if (loaded_descriptor != nullptr)
            return loaded_descriptor;

        auto schema = registry.fetchSchema(id);
        if (collapse_map_entry_)
            schema = collapseProtobufMapEntries(std::move(schema));
        google::protobuf::io::ArrayInputStream input{schema.data(), static_cast<int>(schema.size())};
        google::protobuf::io::Tokenizer tokenizer(&input, this);
        google::protobuf::FileDescriptorProto file_descriptor;
        file_descriptor.set_name(std::to_string(id));
        google::protobuf::compiler::Parser parser;
        parser.RecordErrorsTo(this);
        parser.Parse(&tokenizer, &file_descriptor);

        auto const * descriptor = descriptor_pool.BuildFile(file_descriptor);
        if ((descriptor != nullptr) && descriptor->message_type_count() > 0)
            return descriptor;

        throw Exception(ErrorCodes::INVALID_DATA, "No message type in schema");
    }

    std::mutex mutex;
    KafkaSchemaRegistry registry;
    google::protobuf::DescriptorPool descriptor_pool;
};

ProtobufConfluentRowInputFormat::ProtobufConfluentRowInputFormat(
    ReadBuffer & in_, const Block & header_, Params params_, const FormatSettings & format_settings_)
    : IRowInputFormat(header_, in_, params_, ProcessorID::ProtobufRowInputFormatID)
    , flatten_google_wrappers(format_settings_.protobuf.input_flatten_google_wrappers)
    , collapse_map_entry(format_settings_.protobuf.collapse_schema_registry_map_entry)
    , registry(getConfluentSchemaRegistry(format_settings_))
{
}

bool ProtobufConfluentRowInputFormat::readRow(MutableColumns & columns, RowReadExtension & row_read_extension)
{
    if (in->eof())
        return false;

    auto schema_id = KafkaSchemaRegistry::readSchemaId(*in);

    Int64 indexes_count = 0;
    readVarInt(indexes_count, *in);

    /// Protobuf schemas rarely have deeply nested message types; a reasonable
    /// upper bound prevents allocating huge vectors when the producer omits
    /// the message-index array and the raw protobuf payload is misread as VarInts.
    static constexpr Int64 MAX_INDEXES_COUNT = 128;
    if (indexes_count < 0 || indexes_count > MAX_INDEXES_COUNT)
        throw Exception(
            ErrorCodes::INVALID_DATA,
            "Confluent protobuf message index count {} is out of valid range [0, {}]. "
            "The message may be missing the required message-index array in its wire format.",
            indexes_count,
            MAX_INDEXES_COUNT);

    std::vector<Int64> indexes;
    indexes.reserve(indexes_count < 1 ? 1 : indexes_count);

    if (indexes_count < 1)
    {
        indexes.push_back(0);
    }
    else
    {
        for (Int64 i = 0; i < indexes_count; i++)
        {
            Int64 ind = 0;
            readVarInt(ind, *in);
            indexes.push_back(ind);
        }
    }

    const auto & header = getPort().getHeader();

    ProtobufReader reader{*in};
    ProtobufSchemas::DescriptorHolder descriptor{/*importer_=*/nullptr, registry->getMessageType(schema_id, indexes, collapse_map_entry)};
    auto serializer = ProtobufSerializer::create(
        header.getNames(),
        header.getDataTypes(),
        missing_column_indices,
        descriptor,
        /*with_length_delimiter=*/false,
        /* with_envelope = */ false,
        flatten_google_wrappers,
        reader);

    size_t row_num = columns.empty() ? 0 : columns[0]->size();
    if (row_num == 0u)
        serializer->setColumns(columns.data(), columns.size());

    serializer->readRow(row_num);

    assert(row_read_extension.read_columns.empty());
    if (!missing_column_indices.empty())
    {
        row_read_extension.read_columns.resize(columns.size(), true);
        for (size_t column_idx : missing_column_indices)
            row_read_extension.read_columns[column_idx] = false;
    }
    return true;
}

ProtobufConfluentSchemaReader::ProtobufConfluentSchemaReader(const FormatSettings & format_settings)
    : registry(getConfluentSchemaRegistry(format_settings))
    , subject(format_settings.kafka_schema_registry.subject_name)
    , skip_unsupported_fields(format_settings.protobuf.skip_fields_with_unsupported_types_in_schema_inference)
    , collapse_map_entry(format_settings.protobuf.collapse_schema_registry_map_entry)
{
}

NamesAndTypesList ProtobufConfluentSchemaReader::readSchema()
{
    const auto * const descriptor = registry->getMessageType(subject, collapse_map_entry);
    return protobufSchemaToCHSchema(descriptor, skip_unsupported_fields);
}

ProtobufSchemaWriter::ProtobufSchemaWriter(std::string_view schema_body_, const FormatSettings & settings_)
    : IExternalSchemaWriter(schema_body_, settings_)
    , schema_info(settings.schema.format_schema, "Protobuf", false, settings.schema.is_server, settings.schema.format_schema_path)
{
}

void ProtobufSchemaWriter::validate()
{
    ProtobufSchemas::instance().validateSchema(schema_body);
}

bool ProtobufSchemaWriter::write(bool replace_if_exist)
{
    bool should_clear_cache{false};

    if (std::filesystem::exists(schema_info.absoluteSchemaPath()))
    {
        if (!replace_if_exist)
            return false;

        /// Need to clear the cache for schema replacement, or there will be some strange errors.
        should_clear_cache = true;
    }

    WriteBufferFromFile write_buffer{schema_info.absoluteSchemaPath()};
    write_buffer.write(schema_body.data(), schema_body.size());
    write_buffer.finalize();

    if (should_clear_cache)
        ProtobufSchemas::instance().clear();

    return true;
}
/// proton: ends

void registerProtobufSchemaReader(FormatFactory & factory)
{
    /// proton: starts
    factory.registerExternalSchemaReader("Protobuf", [](const FormatSettings & settings) -> ExternalSchemaReaderPtr {
        if (!settings.schema.format_schema.empty())
            return std::make_shared<ProtobufSchemaReader>(settings);
        return std::make_shared<ProtobufConfluentSchemaReader>(settings);
    });
    factory.registerFileExtension("pb", "Protobuf");
    factory.registerSchemaFileExtension("proto", "Protobuf");

    factory.registerExternalSchemaWriter("Protobuf", [](std::string_view schema_body, const FormatSettings & settings) {
        return std::make_shared<ProtobufSchemaWriter>(schema_body, settings);
    });

    factory.registerExternalSchemaReader("ProtobufSingle", [](const FormatSettings & settings) -> ExternalSchemaReaderPtr {
        if (!settings.schema.format_schema.empty())
            return std::make_shared<ProtobufSchemaReader>(settings);
        return std::make_shared<ProtobufConfluentSchemaReader>(settings);
    });
    /// proton: ends

    for (const auto & name : {"Protobuf", "ProtobufSingle"})
        factory.registerAdditionalInfoForSchemaCacheGetter(
            name, [](const FormatSettings & settings) { return fmt::format("format_schema={}", settings.schema.format_schema); });
}

}

#else

namespace DB
{
class FormatFactory;
void registerInputFormatProtobuf(FormatFactory &) {}
void registerProtobufSchemaReader(FormatFactory &) {}
}

#endif
