#pragma once

#include <Interpreters/Context.h>
#include <Interpreters/IInterpreter.h>
#include <Interpreters/SelectQueryOptions.h>
#include <Parsers/IAST_fwd.h>
#include <DataTypes/DataTypesNumber.h>

/// proton: starts.
#include <Functions/FunctionHelpers.h>
#include <Interpreters/Streaming/HashJoin/JoinStreamDescription.h>
#include <Storages/ColumnsDescription.h>
/// proton: ends.

namespace DB
{

/// proton: starts.
namespace ErrorCodes
{
    extern const int NOT_IMPLEMENTED;
}
/// proton: ends.

class IInterpreterUnionOrSelectQuery : public IInterpreter
{
public:
    IInterpreterUnionOrSelectQuery(const ASTPtr & query_ptr_, const ContextPtr & context_, const SelectQueryOptions & options_)
        : IInterpreterUnionOrSelectQuery(query_ptr_, Context::createCopy(context_), options_)
    {
        if (options.shard_num)
            context->addSpecialScalar(
                "_shard_num",
                Block{{DataTypeUInt32().createColumnConst(1, *options.shard_num), std::make_shared<DataTypeUInt32>(), "_shard_num"}});
        if (options.shard_count)
            context->addSpecialScalar(
                "_shard_count",
                Block{{DataTypeUInt32().createColumnConst(1, *options.shard_count), std::make_shared<DataTypeUInt32>(), "_shard_count"}});
    }

    IInterpreterUnionOrSelectQuery(const ASTPtr & query_ptr_, ContextMutablePtr context_, const SelectQueryOptions & options_)
        : query_ptr(query_ptr_)
        , context(context_)
        , options(options_)
        , max_streams(context->getSettingsRef().max_threads)
    {
        if (options.shard_num)
        {
            context->addSpecialScalar(
                "_shard_num",
                Block{{DataTypeUInt32().createColumnConst(1, *options.shard_num), std::make_shared<DataTypeUInt32>(), "_shard_num"}});

            /// proton: starts.
            /// This is a distributed query on local node, get required shard_num
            context->setShardToRead(*options.shard_num - 1);  /// based on 0
            /// proton: ends.
        }

        if (options.shard_count)
            context->addSpecialScalar(
                "_shard_count",
                Block{{DataTypeUInt32().createColumnConst(1, *options.shard_count), std::make_shared<DataTypeUInt32>(), "_shard_count"}});

        /// proton: starts.
        /// This is a distributed query on remote node, get required shard_num
        if (context->hasQueryContext() && context->getQueryContext()->hasScalar("_shard_num"))
        {
            const auto * column = checkAndGetColumn<ColumnVector<UInt32>>(
                context->getQueryContext()->getScalar("_shard_num").getByPosition(0).column.get());
            if (unlikely(!column))
                throw Exception(ErrorCodes::LOGICAL_ERROR, "Don't get shard num from distributed query on remote node");

            context->setShardToRead(column->getData()[0] - 1);  /// based on 0
        }
        /// proton: ends.
    }

    virtual void buildQueryPlan(QueryPlan & query_plan) = 0;
    QueryPipelineBuilder buildQueryPipeline();

    virtual void ignoreWithTotals() = 0;

    ~IInterpreterUnionOrSelectQuery() override = default;

    Block getSampleBlock() { return result_header; }

    size_t getMaxStreams() const { return max_streams; }

    /// proton: starts
    virtual bool hasAggregation() const = 0;
    virtual bool isStreamingQuery() const = 0;
    virtual bool hasStreamingGlobalAggregation() const = 0;
    virtual bool hasStreamingWindowFunc() const = 0;
    virtual Streaming::DataStreamSemanticEx getDataStreamSemantic() const = 0;

    virtual void assertNoNonDeterministicFunctions(const Names & required, std::string_view msg_prefix) const = 0;

    virtual std::set<String> getGroupByColumns() const = 0;

    virtual bool isConsistentWithoutCheckpoint() const = 0;
    /// proton: ends

    void extendQueryLogElemImpl(QueryLogElement & elem, const ASTPtr &, ContextPtr) const override;
    
    /// Returns whether the query uses the view source from the Context
    /// The view source is a virtual storage that currently only materialized views use to replace the source table
    /// with the incoming block only
    /// This flag is useful to know for how long we can cache scalars generated by this query: If it doesn't use the virtual storage
    /// then we can cache the scalars forever (for any query that doesn't use the virtual storage either), but if it does use the virtual
    /// storage then we can only keep the scalar result around while we are working with that source block
    /// You can find more details about this under ExecuteScalarSubqueriesMatcher::visit
    bool usesViewSource() const { return uses_view_source; }

    /// Add limits from external query.
    void addStorageLimits(const StorageLimitsList & limits);

    ContextPtr getContext() const { return context; }

protected:
    ASTPtr query_ptr;
    ContextMutablePtr context;
    Block result_header;
    SelectQueryOptions options;
    StorageLimitsList storage_limits;

    size_t max_streams = 1;
    bool settings_limit_offset_needed = false;
    bool settings_limit_offset_done = false;
    bool uses_view_source = false;

    /// Set quotas to query pipeline.
    void setQuota(QueryPipeline & pipeline) const;
    /// Add filter from additional_post_filter setting.
    void addAdditionalPostFilter(QueryPlan & plan) const;

    static StorageLimits getStorageLimits(const Context & context, const SelectQueryOptions & options);
};
}
