mv /Users/jameshao/projects/proton/tests/queries/1_stateful/00020_distinct_order_by_distributed.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries/1_stateful/00016_any_if_distributed_cond_always_false.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries_porting/1_stateful/00046_uniq_upto_distributed.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries_porting/1_stateful/00010_quantiles_segfault.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries/1_stateful/00088_global_in_one_shard_and_rows_before_limit.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries/1_stateful/00021_3_select_with_in.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries/1_stateful/00147_global_in_aggregate_function.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries_porting/1_stateful/00082_quantiles.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries/1_stateful/00009_uniq_distributed.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries_porting/1_stateful/00016_any_if_distributed_cond_always_false.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries_porting/1_stateful/00012_sorting_distributed.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries/1_stateful/00012_sorting_distributed.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries_porting/1_stateful/00090_thread_pool_deadlock.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries/1_stateful/00164_quantileBfloat16.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries_porting/1_stateful/00066_sorting_distributed_many_replicas.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries_porting/1_stateful/00067_union_all.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries/1_stateful/00090_thread_pool_deadlock.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries_porting/1_stateful/00021_3_select_with_in.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries/1_stateful/00066_sorting_distributed_many_replicas.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries_porting/1_stateful/00088_global_in_one_shard_and_rows_before_limit.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries_porting/1_stateful/00009_uniq_distributed.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries/1_stateful/00010_quantiles_segfault.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries/1_stateful/00149_quantiles_timing_distributed.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries/1_stateful/00146_aggregate_function_uniq.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries/1_stateful/00082_quantiles.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries/1_stateful/00046_uniq_upto_distributed.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries/bugs/01133_max_result_rows.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries_porting/1_stateful/00020_distinct_order_by_distributed.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
mv /Users/jameshao/projects/proton/tests/queries/1_stateful/00067_union_all.* /Users/jameshao/projects/proton/tests/queries_not_supported/1_stateful/remote/
