name: coinbase
services:
  proton:
    image: d.timeplus.com/timeplus-io/proton:latest
    pull_policy: always
    ports:
      - "3218:3218" # HTTP Streaming
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3218/proton/ping"]
      interval: 5s
      timeout: 15s
      retries: 3
      start_period: 10s

  benthos:
    image: jeffail/benthos:latest
    pull_policy: always
    command: streams
    ports:
      - "4195:4195"

  init-pipeline:
    image: d.timeplus.com/timeplus-io/proton:latest
    command:
      - sh
      - -c
      - |
        curl http://benthos:4195/streams/test -X POST  -d  @/pipeline/pipeline.json
    volumes:
      - ./pipeline:/pipeline
    depends_on:
      proton:
        condition: service_healthy
