SELECT
    extract_url_parameters('http://yandex.ru/?a=b&c=d'),
    extract_url_parameters('http://yandex.ru/?a=b&c=d#e=f'),
    extract_url_parameters('http://yandex.ru/?a&c=d#e=f'),
    extract_url_parameters('http://yandex.ru/?a=b&c=d#e=f&g=h'),
    extract_url_parameters('http://yandex.ru/?a=b&c=d#e'),
    extract_url_parameters('http://yandex.ru/?a=b&c=d#e&g=h'),
    extract_url_parameters('http://yandex.ru/?a=b&c=d#test?e=f&g=h'),
    extract_url_parameters('//yandex.ru/?a=b&c=d'),
    extract_url_parameters('//yandex.ru/?a=b&c=d#e=f'),
    extract_url_parameters('//yandex.ru/?a&c=d#e=f'),
    extract_url_parameters('//yandex.ru/?a=b&c=d#e=f&g=h'),
    extract_url_parameters('//yandex.ru/?a=b&c=d#e'),
    extract_url_parameters('//yandex.ru/?a=b&c=d#e&g=h'),
    extract_url_parameters('//yandex.ru/?a=b&c=d#test?e=f&g=h');

SELECT
    extract_url_parameter_names('http://yandex.ru/?a=b&c=d'),
    extract_url_parameter_names('http://yandex.ru/?a=b&c=d#e=f'),
    extract_url_parameter_names('http://yandex.ru/?a&c=d#e=f'),
    extract_url_parameter_names('http://yandex.ru/?a=b&c=d#e=f&g=h'),
    extract_url_parameter_names('http://yandex.ru/?a=b&c=d#e'),
    extract_url_parameter_names('http://yandex.ru/?a=b&c=d#e&g=h'),
    extract_url_parameter_names('http://yandex.ru/?a=b&c=d#test?e=f&g=h'),
    extract_url_parameter_names('//yandex.ru/?a=b&c=d'),
    extract_url_parameter_names('//yandex.ru/?a=b&c=d#e=f'),
    extract_url_parameter_names('//yandex.ru/?a&c=d#e=f'),
    extract_url_parameter_names('//yandex.ru/?a=b&c=d#e=f&g=h'),
    extract_url_parameter_names('//yandex.ru/?a=b&c=d#e'),
    extract_url_parameter_names('//yandex.ru/?a=b&c=d#e&g=h'),
    extract_url_parameter_names('//yandex.ru/?a=b&c=d#test?e=f&g=h');

SELECT
    extract_url_parameter('http://yandex.ru/?a=b&c=d', 'a'),
    extract_url_parameter('http://yandex.ru/?a=b&c=d', 'c'),
    extract_url_parameter('http://yandex.ru/?a=b&c=d#e=f', 'e'),
    extract_url_parameter('http://yandex.ru/?a&c=d#e=f', 'a'),
    extract_url_parameter('http://yandex.ru/?a&c=d#e=f', 'c'),
    extract_url_parameter('http://yandex.ru/?a&c=d#e=f', 'e'),
    extract_url_parameter('http://yandex.ru/?a=b&c=d#e=f&g=h', 'g'),
    extract_url_parameter('http://yandex.ru/?a=b&c=d#e', 'a'),
    extract_url_parameter('http://yandex.ru/?a=b&c=d#e', 'c'),
    extract_url_parameter('http://yandex.ru/?a=b&c=d#e', 'e'),
    extract_url_parameter('http://yandex.ru/?a=b&c=d#e&g=h', 'c'),
    extract_url_parameter('http://yandex.ru/?a=b&c=d#e&g=h', 'e'),
    extract_url_parameter('http://yandex.ru/?a=b&c=d#e&g=h', 'g'),
    extract_url_parameter('http://yandex.ru/?a=b&c=d#test?e=f&g=h', 'test'),
    extract_url_parameter('http://yandex.ru/?a=b&c=d#test?e=f&g=h', 'e'),
    extract_url_parameter('http://yandex.ru/?a=b&c=d#test?e=f&g=h', 'g'),
    extract_url_parameter('//yandex.ru/?a=b&c=d', 'a'),
    extract_url_parameter('//yandex.ru/?a=b&c=d', 'c'),
    extract_url_parameter('//yandex.ru/?a=b&c=d#e=f', 'e'),
    extract_url_parameter('//yandex.ru/?a&c=d#e=f', 'a'),
    extract_url_parameter('//yandex.ru/?a&c=d#e=f', 'c'),
    extract_url_parameter('//yandex.ru/?a&c=d#e=f', 'e'),
    extract_url_parameter('//yandex.ru/?a=b&c=d#e=f&g=h', 'g'),
    extract_url_parameter('//yandex.ru/?a=b&c=d#e', 'a'),
    extract_url_parameter('//yandex.ru/?a=b&c=d#e', 'c'),
    extract_url_parameter('//yandex.ru/?a=b&c=d#e', 'e'),
    extract_url_parameter('//yandex.ru/?a=b&c=d#e&g=h', 'c'),
    extract_url_parameter('//yandex.ru/?a=b&c=d#e&g=h', 'e'),
    extract_url_parameter('//yandex.ru/?a=b&c=d#e&g=h', 'g'),
    extract_url_parameter('//yandex.ru/?a=b&c=d#test?e=f&g=h', 'test'),
    extract_url_parameter('//yandex.ru/?a=b&c=d#test?e=f&g=h', 'e'),
    extract_url_parameter('//yandex.ru/?a=b&c=d#test?e=f&g=h', 'g');

SELECT
    cut_url_parameter('http://yandex.ru/?a=b&c=d', 'a'),
    cut_url_parameter('http://yandex.ru/?a=b&c=d', 'c'),
    cut_url_parameter('http://yandex.ru/?a=b&c=d#e=f', 'e'),
    cut_url_parameter('http://yandex.ru/?a&c=d#e=f', 'a'),
    cut_url_parameter('http://yandex.ru/?a&c=d#e=f', 'c'),
    cut_url_parameter('http://yandex.ru/?a&c=d#e=f', 'e'),
    cut_url_parameter('http://yandex.ru/?a=b&c=d#e=f&g=h', 'g'),
    cut_url_parameter('http://yandex.ru/?a=b&c=d#e', 'a'),
    cut_url_parameter('http://yandex.ru/?a=b&c=d#e', 'c'),
    cut_url_parameter('http://yandex.ru/?a=b&c=d#e', 'e'),
    cut_url_parameter('http://yandex.ru/?a=b&c=d#e&g=h', 'c'),
    cut_url_parameter('http://yandex.ru/?a=b&c=d#e&g=h', 'e'),
    cut_url_parameter('http://yandex.ru/?a=b&c=d#e&g=h', 'g'),
    cut_url_parameter('http://yandex.ru/?a=b&c=d#test?e=f&g=h', 'test'),
    cut_url_parameter('http://yandex.ru/?a=b&c=d#test?e=f&g=h', 'e'),
    cut_url_parameter('http://yandex.ru/?a=b&c=d#test?e=f&g=h', 'g'),
    cut_url_parameter('//yandex.ru/?a=b&c=d', 'a'),
    cut_url_parameter('//yandex.ru/?a=b&c=d', 'c'),
    cut_url_parameter('//yandex.ru/?a=b&c=d#e=f', 'e'),
    cut_url_parameter('//yandex.ru/?a&c=d#e=f', 'a'),
    cut_url_parameter('//yandex.ru/?a&c=d#e=f', 'c'),
    cut_url_parameter('//yandex.ru/?a&c=d#e=f', 'e'),
    cut_url_parameter('//yandex.ru/?a=b&c=d#e=f&g=h', 'g'),
    cut_url_parameter('//yandex.ru/?a=b&c=d#e', 'a'),
    cut_url_parameter('//yandex.ru/?a=b&c=d#e', 'c'),
    cut_url_parameter('//yandex.ru/?a=b&c=d#e', 'e'),
    cut_url_parameter('//yandex.ru/?a=b&c=d#e&g=h', 'c'),
    cut_url_parameter('//yandex.ru/?a=b&c=d#e&g=h', 'e'),
    cut_url_parameter('//yandex.ru/?a=b&c=d#e&g=h', 'g'),
    cut_url_parameter('//yandex.ru/?a=b&c=d#test?e=f&g=h', 'test'),
    cut_url_parameter('//yandex.ru/?a=b&c=d#test?e=f&g=h', 'e'),
    cut_url_parameter('//yandex.ru/?a=b&c=d#test?e=f&g=h', 'g');


SELECT
    extract_url_parameters(materialize('http://yandex.ru/?a=b&c=d')),
    extract_url_parameters(materialize('http://yandex.ru/?a=b&c=d#e=f')),
    extract_url_parameters(materialize('http://yandex.ru/?a&c=d#e=f')),
    extract_url_parameters(materialize('http://yandex.ru/?a=b&c=d#e=f&g=h')),
    extract_url_parameters(materialize('http://yandex.ru/?a=b&c=d#e')),
    extract_url_parameters(materialize('http://yandex.ru/?a=b&c=d#e&g=h')),
    extract_url_parameters(materialize('http://yandex.ru/?a=b&c=d#test?e=f&g=h')),
    extract_url_parameters(materialize('//yandex.ru/?a=b&c=d')),
    extract_url_parameters(materialize('//yandex.ru/?a=b&c=d#e=f')),
    extract_url_parameters(materialize('//yandex.ru/?a&c=d#e=f')),
    extract_url_parameters(materialize('//yandex.ru/?a=b&c=d#e=f&g=h')),
    extract_url_parameters(materialize('//yandex.ru/?a=b&c=d#e')),
    extract_url_parameters(materialize('//yandex.ru/?a=b&c=d#e&g=h')),
    extract_url_parameters(materialize('//yandex.ru/?a=b&c=d#test?e=f&g=h'));

SELECT
    extract_url_parameter_names(materialize('http://yandex.ru/?a=b&c=d')),
    extract_url_parameter_names(materialize('http://yandex.ru/?a=b&c=d#e=f')),
    extract_url_parameter_names(materialize('http://yandex.ru/?a&c=d#e=f')),
    extract_url_parameter_names(materialize('http://yandex.ru/?a=b&c=d#e=f&g=h')),
    extract_url_parameter_names(materialize('http://yandex.ru/?a=b&c=d#e')),
    extract_url_parameter_names(materialize('http://yandex.ru/?a=b&c=d#e&g=h')),
    extract_url_parameter_names(materialize('http://yandex.ru/?a=b&c=d#test?e=f&g=h')),
    extract_url_parameter_names(materialize('//yandex.ru/?a=b&c=d')),
    extract_url_parameter_names(materialize('//yandex.ru/?a=b&c=d#e=f')),
    extract_url_parameter_names(materialize('//yandex.ru/?a&c=d#e=f')),
    extract_url_parameter_names(materialize('//yandex.ru/?a=b&c=d#e=f&g=h')),
    extract_url_parameter_names(materialize('//yandex.ru/?a=b&c=d#e')),
    extract_url_parameter_names(materialize('//yandex.ru/?a=b&c=d#e&g=h')),
    extract_url_parameter_names(materialize('//yandex.ru/?a=b&c=d#test?e=f&g=h'));

SELECT
    extract_url_parameter(materialize('http://yandex.ru/?a=b&c=d'), 'a'),
    extract_url_parameter(materialize('http://yandex.ru/?a=b&c=d'), 'c'),
    extract_url_parameter(materialize('http://yandex.ru/?a=b&c=d#e=f'), 'e'),
    extract_url_parameter(materialize('http://yandex.ru/?a&c=d#e=f'), 'a'),
    extract_url_parameter(materialize('http://yandex.ru/?a&c=d#e=f'), 'c'),
    extract_url_parameter(materialize('http://yandex.ru/?a&c=d#e=f'), 'e'),
    extract_url_parameter(materialize('http://yandex.ru/?a=b&c=d#e=f&g=h'), 'g'),
    extract_url_parameter(materialize('http://yandex.ru/?a=b&c=d#e'), 'a'),
    extract_url_parameter(materialize('http://yandex.ru/?a=b&c=d#e'), 'c'),
    extract_url_parameter(materialize('http://yandex.ru/?a=b&c=d#e'), 'e'),
    extract_url_parameter(materialize('http://yandex.ru/?a=b&c=d#e&g=h'), 'c'),
    extract_url_parameter(materialize('http://yandex.ru/?a=b&c=d#e&g=h'), 'e'),
    extract_url_parameter(materialize('http://yandex.ru/?a=b&c=d#e&g=h'), 'g'),
    extract_url_parameter(materialize('http://yandex.ru/?a=b&c=d#test?e=f&g=h'), 'test'),
    extract_url_parameter(materialize('http://yandex.ru/?a=b&c=d#test?e=f&g=h'), 'e'),
    extract_url_parameter(materialize('http://yandex.ru/?a=b&c=d#test?e=f&g=h'), 'g'),
    extract_url_parameter(materialize('//yandex.ru/?a=b&c=d'), 'a'),
    extract_url_parameter(materialize('//yandex.ru/?a=b&c=d'), 'c'),
    extract_url_parameter(materialize('//yandex.ru/?a=b&c=d#e=f'), 'e'),
    extract_url_parameter(materialize('//yandex.ru/?a&c=d#e=f'), 'a'),
    extract_url_parameter(materialize('//yandex.ru/?a&c=d#e=f'), 'c'),
    extract_url_parameter(materialize('//yandex.ru/?a&c=d#e=f'), 'e'),
    extract_url_parameter(materialize('//yandex.ru/?a=b&c=d#e=f&g=h'), 'g'),
    extract_url_parameter(materialize('//yandex.ru/?a=b&c=d#e'), 'a'),
    extract_url_parameter(materialize('//yandex.ru/?a=b&c=d#e'), 'c'),
    extract_url_parameter(materialize('//yandex.ru/?a=b&c=d#e'), 'e'),
    extract_url_parameter(materialize('//yandex.ru/?a=b&c=d#e&g=h'), 'c'),
    extract_url_parameter(materialize('//yandex.ru/?a=b&c=d#e&g=h'), 'e'),
    extract_url_parameter(materialize('//yandex.ru/?a=b&c=d#e&g=h'), 'g'),
    extract_url_parameter(materialize('//yandex.ru/?a=b&c=d#test?e=f&g=h'), 'test'),
    extract_url_parameter(materialize('//yandex.ru/?a=b&c=d#test?e=f&g=h'), 'e'),
    extract_url_parameter(materialize('//yandex.ru/?a=b&c=d#test?e=f&g=h'), 'g');

SELECT
    cut_url_parameter(materialize('http://yandex.ru/?a=b&c=d'), 'a'),
    cut_url_parameter(materialize('http://yandex.ru/?a=b&c=d'), 'c'),
    cut_url_parameter(materialize('http://yandex.ru/?a=b&c=d#e=f'), 'e'),
    cut_url_parameter(materialize('http://yandex.ru/?a&c=d#e=f'), 'a'),
    cut_url_parameter(materialize('http://yandex.ru/?a&c=d#e=f'), 'c'),
    cut_url_parameter(materialize('http://yandex.ru/?a&c=d#e=f'), 'e'),
    cut_url_parameter(materialize('http://yandex.ru/?a=b&c=d#e=f&g=h'), 'g'),
    cut_url_parameter(materialize('http://yandex.ru/?a=b&c=d#e'), 'a'),
    cut_url_parameter(materialize('http://yandex.ru/?a=b&c=d#e'), 'c'),
    cut_url_parameter(materialize('http://yandex.ru/?a=b&c=d#e'), 'e'),
    cut_url_parameter(materialize('http://yandex.ru/?a=b&c=d#e&g=h'), 'c'),
    cut_url_parameter(materialize('http://yandex.ru/?a=b&c=d#e&g=h'), 'e'),
    cut_url_parameter(materialize('http://yandex.ru/?a=b&c=d#e&g=h'), 'g'),
    cut_url_parameter(materialize('http://yandex.ru/?a=b&c=d#test?e=f&g=h'), 'test'),
    cut_url_parameter(materialize('http://yandex.ru/?a=b&c=d#test?e=f&g=h'), 'e'),
    cut_url_parameter(materialize('http://yandex.ru/?a=b&c=d#test?e=f&g=h'), 'g'),
    cut_url_parameter(materialize('//yandex.ru/?a=b&c=d'), 'a'),
    cut_url_parameter(materialize('//yandex.ru/?a=b&c=d'), 'c'),
    cut_url_parameter(materialize('//yandex.ru/?a=b&c=d#e=f'), 'e'),
    cut_url_parameter(materialize('//yandex.ru/?a&c=d#e=f'), 'a'),
    cut_url_parameter(materialize('//yandex.ru/?a&c=d#e=f'), 'c'),
    cut_url_parameter(materialize('//yandex.ru/?a&c=d#e=f'), 'e'),
    cut_url_parameter(materialize('//yandex.ru/?a=b&c=d#e=f&g=h'), 'g'),
    cut_url_parameter(materialize('//yandex.ru/?a=b&c=d#e'), 'a'),
    cut_url_parameter(materialize('//yandex.ru/?a=b&c=d#e'), 'c'),
    cut_url_parameter(materialize('//yandex.ru/?a=b&c=d#e'), 'e'),
    cut_url_parameter(materialize('//yandex.ru/?a=b&c=d#e&g=h'), 'c'),
    cut_url_parameter(materialize('//yandex.ru/?a=b&c=d#e&g=h'), 'e'),
    cut_url_parameter(materialize('//yandex.ru/?a=b&c=d#e&g=h'), 'g'),
    cut_url_parameter(materialize('//yandex.ru/?a=b&c=d#test?e=f&g=h'), 'test'),
    cut_url_parameter(materialize('//yandex.ru/?a=b&c=d#test?e=f&g=h'), 'e'),
    cut_url_parameter(materialize('//yandex.ru/?a=b&c=d#test?e=f&g=h'), 'g');
