SELECT position_case_insensitive_utf8(concat('иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat(' иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('  иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('   иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('    иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('     иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('      иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('       иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('        иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('         иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('          иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('           иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('            иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('             иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('              иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('               иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('                иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('                 иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('                  иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('                   иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('                    иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('                     иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive_utf8(concat('                      иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;

SELECT position_case_insensitive(concat('иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat(' иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('  иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('   иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('    иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('     иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('      иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('       иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('        иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('         иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('          иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('           иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('            иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('             иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('              иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('               иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('                иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('                 иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('                  иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('                   иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('                    иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('                     иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_case_insensitive(concat('                      иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;

SELECT position_utf8(concat('иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat(' иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('  иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('   иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('    иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('     иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('      иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('       иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('        иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('         иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('          иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('           иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('            иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('             иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('              иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('               иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('                иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('                 иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('                  иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('                   иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('                    иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('                     иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position_utf8(concat('                      иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;

SELECT position(concat('иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat(' иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('  иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('   иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('    иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('     иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('      иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('       иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('        иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('         иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('          иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('           иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('            иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('             иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('              иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('               иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('                иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('                 иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('                  иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('                   иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('                    иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('                     иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;
SELECT position(concat('                      иголка.ру', array_string_concat(array_map(x -> ' ', range(20000)))), 'иголка.ру') AS res;

SELECT position_case_insensitive_utf8(materialize('test ß test'), 'ß') AS res;
SELECT position_case_insensitive_utf8(materialize('test AaßAa test'), 'aßa') AS res;
SELECT position_case_insensitive_utf8(materialize('test A1ß2a test'), '1ß2') AS res;
SELECT position_case_insensitive_utf8(materialize('xẞyyaa1ẞ1yzẞXẞẞ1ẞẞ1bctest'), 'aa1ẞ1Yzßxßß1ßß1BC') AS res;

SELECT position_case_insensitive_utf8(materialize(concat('test a1ßAa test', array_string_concat(array_map(x -> ' ', range(20000))))), 'a1ẞaa') AS res;
SELECT position_case_insensitive_utf8(materialize(concat(' test a1ßAa test', array_string_concat(array_map(x -> ' ', range(20000))))), 'a1ẞaa') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('  test a1ßAa test', array_string_concat(array_map(x -> ' ', range(20000))))), 'a1ẞaa') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('   test a1ßAa test', array_string_concat(array_map(x -> ' ', range(20000))))), 'a1ẞaa') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('    test a1ßAa test', array_string_concat(array_map(x -> ' ', range(20000))))), 'a1ẞaa') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('     test a1ßAa test', array_string_concat(array_map(x -> ' ', range(20000))))), 'a1ẞaa') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('      test a1ßAa test', array_string_concat(array_map(x -> ' ', range(20000))))), 'a1ẞaa') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('       test a1ßAa test', array_string_concat(array_map(x -> ' ', range(20000))))), 'a1ẞaa') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('        test a1ßAa test', array_string_concat(array_map(x -> ' ', range(20000))))), 'a1ẞaa') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('         test a1ßAa test', array_string_concat(array_map(x -> ' ', range(20000))))), 'a1ẞaa') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('          test a1ßAa test', array_string_concat(array_map(x -> ' ', range(20000))))), 'a1ẞaa') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('           test a1ßAa test', array_string_concat(array_map(x -> ' ', range(20000))))), 'a1ẞaa') AS res;

SELECT position_case_insensitive_utf8(materialize(concat('xẞyyaa1ẞ1yzẞXẞẞ1ẞẞ1bctest', array_string_concat(array_map(x -> ' ', range(20000))))), 'aa1ẞ1Yzßxßß1ßß1BC') AS res;
SELECT position_case_insensitive_utf8(materialize(concat(' xẞyyaa1ẞ1yzẞXẞẞ1ẞẞ1bctest', array_string_concat(array_map(x -> ' ', range(20000))))), 'aa1ẞ1Yzßxßß1ßß1BC') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('  xẞyyaa1ẞ1yzẞXẞẞ1ẞẞ1bctest', array_string_concat(array_map(x -> ' ', range(20000))))), 'aa1ẞ1Yzßxßß1ßß1BC') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('   xẞyyaa1ẞ1yzẞXẞẞ1ẞẞ1bctest', array_string_concat(array_map(x -> ' ', range(20000))))), 'aa1ẞ1Yzßxßß1ßß1BC') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('    xẞyyaa1ẞ1yzẞXẞẞ1ẞẞ1bctest', array_string_concat(array_map(x -> ' ', range(20000))))), 'aa1ẞ1Yzßxßß1ßß1BC') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('     xẞyyaa1ẞ1yzẞXẞẞ1ẞẞ1bctest', array_string_concat(array_map(x -> ' ', range(20000))))), 'aa1ẞ1Yzßxßß1ßß1BC') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('      xẞyyaa1ẞ1yzẞXẞẞ1ẞẞ1bctest', array_string_concat(array_map(x -> ' ', range(20000))))), 'aa1ẞ1Yzßxßß1ßß1BC') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('       xẞyyaa1ẞ1yzẞXẞẞ1ẞẞ1bctest', array_string_concat(array_map(x -> ' ', range(20000))))), 'aa1ẞ1Yzßxßß1ßß1BC') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('        xẞyyaa1ẞ1yzẞXẞẞ1ẞẞ1bctest', array_string_concat(array_map(x -> ' ', range(20000))))), 'aa1ẞ1Yzßxßß1ßß1BC') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('         xẞyyaa1ẞ1yzẞXẞẞ1ẞẞ1bctest', array_string_concat(array_map(x -> ' ', range(20000))))), 'aa1ẞ1Yzßxßß1ßß1BC') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('          xẞyyaa1ẞ1yzẞXẞẞ1ẞẞ1bctest', array_string_concat(array_map(x -> ' ', range(20000))))), 'aa1ẞ1Yzßxßß1ßß1BC') AS res;
SELECT position_case_insensitive_utf8(materialize(concat('           xẞyyaa1ẞ1yzẞXẞẞ1ẞẞ1bctest', array_string_concat(array_map(x -> ' ', range(20000))))), 'aa1ẞ1Yzßxßß1ßß1BC') AS res;
