SELECT
to_float64('inf'),
to_float64('-inf'),
to_float64('INF'),
to_float64('-INF'),
to_float64('Infinity'),
to_float64('-Infinity'),
to_float64('nan'),
to_float64('-nan'),
to_float64('NAN'),
to_float64('-NAN'),
to_float64('NaN'),
to_float64('-NaN'),

to_float64_or_zero('in'),
to_float64_or_zero('-in'),
to_float64_or_zero('INFi'),
to_float64_or_zero('-INFi'),
to_float64_or_zero('Infinit'),
to_float64_or_zero('-Infinit'),
to_float64_or_zero('na'),
to_float64_or_zero('-na'),
to_float64_or_zero('NANo'),
to_float64_or_zero('-NANo'),
to_float64_or_zero('NaN+'),
to_float64_or_zero('-NaNa'),
to_float64_or_zero('+Na'),

to_float32('inf'),
to_float32('-inf'),
to_float32('INF'),
to_float32('-INF'),
to_float32('Infinity'),
to_float32('-Infinity'),
to_float32('nan'),
to_float32('-nan'),
to_float32('NAN'),
to_float32('-NAN'),
to_float32('NaN'),
to_float32('-NaN'),

to_float32_or_zero('in'),
to_float32_or_zero('-in'),
to_float32_or_zero('INFi'),
to_float32_or_zero('-INFi'),
to_float32_or_zero('Infinit'),
to_float32_or_zero('-Infinit'),
to_float32_or_zero('na'),
to_float32_or_zero('-na'),
to_float32_or_zero('NANo'),
to_float32_or_zero('-NANo'),
to_float32_or_zero('NaN+'),
to_float32_or_zero('-NaNa'),
to_float32_or_zero('+Na')

FORMAT TabSeparated;
