select array_compact([0]);
select array_compact([1]);
select array_compact([2]);
select array_compact([1,1]);
select array_compact([1,2]);
select array_compact([1,1,2]);
select array_compact([1,2,1]);
select array_compact([2,1,1]);
select array_compact([1,2,2,3,3,3,4,4,4,4,5,5,5,5,5]);
SELECT array_compact(array_map(x->0, [NULL]));
SELECT to_string(array_compact(array_map(x->0, [NULL])));
