-- Tags: no-parallel

SHOW STREAMS NOT LIKE '%';

DROP DATABASE IF EXISTS test_01073;
CREATE DATABASE test_01073;
USE test_01073;

SHOW STREAMS;
SELECT '---';
CREATE STREAM test1 (x uint8) ENGINE = Memory;
CREATE STREAM test2 (x uint8) ENGINE = Memory;

SHOW STREAMS;
SELECT '--';
SHOW STREAMS LIKE 'tes%';
SELECT '--';
SHOW STREAMS NOT LIKE 'tes%';
SELECT '--';
SHOW STREAMS LIKE 'tes%1';
SELECT '--';
SHOW STREAMS NOT LIKE 'tes%2';

SELECT '---';
SHOW STREAMS FROM test_01073;
SELECT '--';
SHOW STREAMS FROM test_01073 LIKE 'tes%';
SELECT '--';
SHOW STREAMS FROM test_01073 NOT LIKE 'tes%';
SELECT '--';
SHOW STREAMS FROM test_01073 LIKE 'tes%1';
SELECT '--';
SHOW STREAMS FROM test_01073 NOT LIKE 'tes%2';

DROP DATABASE test_01073;
