SELECT DIV AS MOD FROM (SELECT 1 as  `DIV`) FORMAT TSVWithNames;
SELECT DIV AS  `MOD` FROM (SELECT 1 as  `DIV`) FORMAT TSVWithNames;
SELECT DIV MOD 1 FROM (SELECT 1 as  `DIV`) FORMAT TSVWithNames;
SELECT 1 DIV `MOD` AS `DIV` FROM (SELECT 1 AS  `MOD`) FORMAT TSVWithNames;

SELECT DIV AS mod FROM (SELECT 1 as  `DIV`) FORMAT TSVWithNames;
SELECT DIV AS  `MOD` FROM (SELECT 1 as  `DIV`) FORMAT TSVWithNames;
SELECT DIV mod 1 FROM (SELECT 1 as  `DIV`) FORMAT TSVWithNames;
SELECT 1 div `MOD` AS  `DIV` FROM (SELECT 1 AS  `MOD`) FORMAT TSVWithNames;
