SELECT 'into string';
SELECT reinterpret(49, 'string');
SELECT 'into fixed_string';
SELECT reinterpret(49, 'fixed_string(1)');
SELECT reinterpret(49, 'fixed_string(2)');
SELECT reinterpret(49, 'fixed_string(3)');
SELECT reinterpret(49, 'fixed_string(4)');
SELECT reinterpret_as_fixed_string(49);
SELECT 'into Numeric Representable';
SELECT 'integer and integer types';
SELECT reinterpret(257, 'uint8'), reinterpret_as_uint8(257);
SELECT reinterpret(257, 'int8'), reinterpret_as_int8(257);
SELECT reinterpret(257, 'uint16'), reinterpret_as_uint16(257);
SELECT reinterpret(257, 'int16'), reinterpret_as_int16(257);
SELECT reinterpret(257, 'uint32'), reinterpret_as_uint32(257);
SELECT reinterpret(257, 'int32'), reinterpret_as_int32(257);
SELECT reinterpret(257, 'uint64'), reinterpret_as_uint64(257);
SELECT reinterpret(257, 'int64'), reinterpret_as_int64(257);
SELECT reinterpret(257, 'int128'), reinterpret_as_int128(257);
SELECT reinterpret(257, 'uint256'), reinterpret_as_uint256(257);
SELECT reinterpret(257, 'int256'), reinterpret_as_int256(257);
SELECT 'integer and float types';
SELECT reinterpret(to_float32(0.2), 'uint32'), reinterpret_as_uint32(to_float32(0.2));
SELECT reinterpret(to_float64(0.2), 'uint64'), reinterpret_as_uint64(to_float64(0.2));
SELECT reinterpret_as_float32(a), reinterpret_as_uint32(to_float32(0.2)) as a;
SELECT reinterpret_as_float64(a), reinterpret_as_uint64(to_float64(0.2)) as a;
SELECT 'integer and string types';
SELECT reinterpret(a, 'string'), reinterpret_as_string(a), reinterpret_as_uint8('1') as a;
SELECT reinterpret(a, 'string'), reinterpret_as_string(a), reinterpret_as_uint8('11') as a;
SELECT reinterpret(a, 'string'), reinterpret_as_string(a), reinterpret_as_uint16('11') as a;
SELECT 'Dates';
SELECT reinterpret(0, 'Date'), reinterpret('', 'Date');
SELECT reinterpret(0, 'DateTime(''Asia/Istanbul'')'), reinterpret('', 'DateTime(''Asia/Istanbul'')');
SELECT reinterpret(0, 'DateTime64(3, ''Asia/Istanbul'')'), reinterpret('', 'DateTime64(3, ''Asia/Istanbul'')');
SELECT 'decimals';
SELECT reinterpret(to_decimal32(5, 2), 'decimal32(2)'), reinterpret('1', 'decimal32(2)');
SELECT reinterpret(to_decimal64(5, 2), 'decimal64(2)'), reinterpret('1', 'decimal64(2)');;
SELECT reinterpret(to_decimal128(5, 2), 'decimal128(2)'), reinterpret('1', 'decimal128(2)');
SELECT reinterpret(to_decimal256(5, 2), 'decimal256(2)'), reinterpret('1', 'decimal256(2)');
SELECT reinterpret(to_datetime64(0, 0), 'decimal64(2)');
SELECT 'ReinterpretErrors';
SELECT reinterpret('123', 'fixed_string(1)'); -- {serverError 43}
