SELECT to_year(d) AS y, count()
FROM ( SELECT today() AS d WHERE 0)
GROUP BY y
ORDER BY y ASC WITH FILL FROM 2019 TO 2023;

SELECT to_year(d) AS y, count()
FROM ( SELECT today() AS d WHERE 0)
GROUP BY y
ORDER BY y ASC WITH FILL FROM 2019;

SELECT to_year(d) AS y, count()
FROM ( SELECT today() AS d WHERE 0)
GROUP BY y
ORDER BY y ASC WITH FILL TO 2023;

SELECT to_year(d) AS y, count()
FROM ( SELECT today() AS d WHERE 0)
GROUP BY y
ORDER BY y ASC WITH FILL;
