-- { echoOn }
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'G'), format_datetime_in_joda_syntax(datetime64, 'G'), format_datetime_in_joda_syntax(date, 'G'), format_datetime_in_joda_syntax(date32, 'G');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'GG'), format_datetime_in_joda_syntax(datetime64, 'GG'), format_datetime_in_joda_syntax(date, 'GG'), format_datetime_in_joda_syntax(date32, 'GG');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'GGG'), format_datetime_in_joda_syntax(datetime64, 'GGG'), format_datetime_in_joda_syntax(date, 'GGG'), format_datetime_in_joda_syntax(date32, 'GGG');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'GGGG'), format_datetime_in_joda_syntax(datetime64, 'GGGG'), format_datetime_in_joda_syntax(date, 'GGGG'), format_datetime_in_joda_syntax(date32, 'GGGG');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'GGGGG'), format_datetime_in_joda_syntax(datetime64, 'GGGGG'), format_datetime_in_joda_syntax(date, 'GGGGG'), format_datetime_in_joda_syntax(date32, 'GGGGG');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'C'), format_datetime_in_joda_syntax(datetime64, 'C'), format_datetime_in_joda_syntax(date, 'C'), format_datetime_in_joda_syntax(date32, 'C');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'CC'), format_datetime_in_joda_syntax(datetime64, 'CC'), format_datetime_in_joda_syntax(date, 'CC'), format_datetime_in_joda_syntax(date32, 'CC');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'CCC'), format_datetime_in_joda_syntax(datetime64, 'CCC'), format_datetime_in_joda_syntax(date, 'CCC'), format_datetime_in_joda_syntax(date32, 'CCC');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'Y'), format_datetime_in_joda_syntax(datetime64, 'Y'), format_datetime_in_joda_syntax(date, 'Y'), format_datetime_in_joda_syntax(date32, 'Y');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'YY'), format_datetime_in_joda_syntax(datetime64, 'YY'), format_datetime_in_joda_syntax(date, 'YY'), format_datetime_in_joda_syntax(date32, 'YY');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'YYY'), format_datetime_in_joda_syntax(datetime64, 'YYY'), format_datetime_in_joda_syntax(date, 'YYY'), format_datetime_in_joda_syntax(date32, 'YYY');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'YYYY'), format_datetime_in_joda_syntax(datetime64, 'YYYY'), format_datetime_in_joda_syntax(date, 'YYYY'), format_datetime_in_joda_syntax(date32, 'YYYY');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'YYYYY'), format_datetime_in_joda_syntax(datetime64, 'YYYYY'), format_datetime_in_joda_syntax(date, 'YYYYY'), format_datetime_in_joda_syntax(date32, 'YYYYY');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'e'), format_datetime_in_joda_syntax(datetime64, 'e'), format_datetime_in_joda_syntax(date, 'e'), format_datetime_in_joda_syntax(date32, 'e');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'ee'), format_datetime_in_joda_syntax(datetime64, 'ee'), format_datetime_in_joda_syntax(date, 'ee'), format_datetime_in_joda_syntax(date32, 'ee');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'E'), format_datetime_in_joda_syntax(datetime64, 'E'), format_datetime_in_joda_syntax(date, 'E'), format_datetime_in_joda_syntax(date32, 'E');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'EE'), format_datetime_in_joda_syntax(datetime64, 'EE'), format_datetime_in_joda_syntax(date, 'EE'), format_datetime_in_joda_syntax(date32, 'EE');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'EEE'), format_datetime_in_joda_syntax(datetime64, 'EEE'), format_datetime_in_joda_syntax(date, 'EEE'), format_datetime_in_joda_syntax(date32, 'EEE');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'EEEE'), format_datetime_in_joda_syntax(datetime64, 'EEEE'), format_datetime_in_joda_syntax(date, 'EEEE'), format_datetime_in_joda_syntax(date32, 'EEEE');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'EEEEE'), format_datetime_in_joda_syntax(datetime64, 'EEEEE'), format_datetime_in_joda_syntax(date, 'EEEEE'), format_datetime_in_joda_syntax(date32, 'EEEEE');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'y'), format_datetime_in_joda_syntax(datetime64, 'y'), format_datetime_in_joda_syntax(date, 'y'), format_datetime_in_joda_syntax(date32, 'y');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'yy'), format_datetime_in_joda_syntax(datetime64, 'yy'), format_datetime_in_joda_syntax(date, 'yy'), format_datetime_in_joda_syntax(date32, 'yy');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'yyy'), format_datetime_in_joda_syntax(datetime64, 'yyy'), format_datetime_in_joda_syntax(date, 'yyy'), format_datetime_in_joda_syntax(date32, 'yyy');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'yyyy'), format_datetime_in_joda_syntax(datetime64, 'yyyy'), format_datetime_in_joda_syntax(date, 'yyyy'), format_datetime_in_joda_syntax(date32, 'yyyy');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'yyyyy'), format_datetime_in_joda_syntax(datetime64, 'yyyyy'), format_datetime_in_joda_syntax(date, 'yyyyy'), format_datetime_in_joda_syntax(date32, 'yyyyy');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'D'), format_datetime_in_joda_syntax(datetime64, 'D'), format_datetime_in_joda_syntax(date, 'D'), format_datetime_in_joda_syntax(date32, 'D');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'DD'), format_datetime_in_joda_syntax(datetime64, 'DD'), format_datetime_in_joda_syntax(date, 'DD'), format_datetime_in_joda_syntax(date32, 'DD');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'DDD'), format_datetime_in_joda_syntax(datetime64, 'DDD'), format_datetime_in_joda_syntax(date, 'DDD'), format_datetime_in_joda_syntax(date32, 'DDD');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'M'), format_datetime_in_joda_syntax(datetime64, 'M'), format_datetime_in_joda_syntax(date, 'M'), format_datetime_in_joda_syntax(date32, 'M');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'MM'), format_datetime_in_joda_syntax(datetime64, 'MM'), format_datetime_in_joda_syntax(date, 'MM'), format_datetime_in_joda_syntax(date32, 'MM');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'MMM'), format_datetime_in_joda_syntax(datetime64, 'MMM'), format_datetime_in_joda_syntax(date, 'MMM'), format_datetime_in_joda_syntax(date32, 'MMM');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'MMMM'), format_datetime_in_joda_syntax(datetime64, 'MMMM'), format_datetime_in_joda_syntax(date, 'MMMM'), format_datetime_in_joda_syntax(date32, 'MMMM');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'd'), format_datetime_in_joda_syntax(datetime64, 'd'), format_datetime_in_joda_syntax(date, 'd'), format_datetime_in_joda_syntax(date32, 'd');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'dd'), format_datetime_in_joda_syntax(datetime64, 'dd'), format_datetime_in_joda_syntax(date, 'dd'), format_datetime_in_joda_syntax(date32, 'dd');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'ddd'), format_datetime_in_joda_syntax(datetime64, 'ddd'), format_datetime_in_joda_syntax(date, 'ddd'), format_datetime_in_joda_syntax(date32, 'ddd');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'a'), format_datetime_in_joda_syntax(datetime64, 'a'), format_datetime_in_joda_syntax(date, 'a'), format_datetime_in_joda_syntax(date32, 'a');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'aa'), format_datetime_in_joda_syntax(datetime64, 'aa'), format_datetime_in_joda_syntax(date, 'aa'), format_datetime_in_joda_syntax(date32, 'aa');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'aaa'), format_datetime_in_joda_syntax(datetime64, 'aaa'), format_datetime_in_joda_syntax(date, 'aaa'), format_datetime_in_joda_syntax(date32, 'aaa');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'K'), format_datetime_in_joda_syntax(datetime64, 'K'), format_datetime_in_joda_syntax(date, 'K'), format_datetime_in_joda_syntax(date32, 'K');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'KK'), format_datetime_in_joda_syntax(datetime64, 'KK'), format_datetime_in_joda_syntax(date, 'KK'), format_datetime_in_joda_syntax(date32, 'KK');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'KKK'), format_datetime_in_joda_syntax(datetime64, 'KKK'), format_datetime_in_joda_syntax(date, 'KKK'), format_datetime_in_joda_syntax(date32, 'KKK');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'h'), format_datetime_in_joda_syntax(datetime64, 'h'), format_datetime_in_joda_syntax(date, 'h'), format_datetime_in_joda_syntax(date32, 'h');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'hh'), format_datetime_in_joda_syntax(datetime64, 'hh'), format_datetime_in_joda_syntax(date, 'hh'), format_datetime_in_joda_syntax(date32, 'hh');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'hhh'), format_datetime_in_joda_syntax(datetime64, 'hhh'), format_datetime_in_joda_syntax(date, 'hhh'), format_datetime_in_joda_syntax(date32, 'hhh');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'H'), format_datetime_in_joda_syntax(datetime64, 'H'), format_datetime_in_joda_syntax(date, 'H'), format_datetime_in_joda_syntax(date32, 'H');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'HH'), format_datetime_in_joda_syntax(datetime64, 'HH'), format_datetime_in_joda_syntax(date, 'HH'), format_datetime_in_joda_syntax(date32, 'HH');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'HHH'), format_datetime_in_joda_syntax(datetime64, 'HHH'), format_datetime_in_joda_syntax(date, 'HHH'), format_datetime_in_joda_syntax(date32, 'HHH');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'k'), format_datetime_in_joda_syntax(datetime64, 'k'), format_datetime_in_joda_syntax(date, 'k'), format_datetime_in_joda_syntax(date32, 'k');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'kk'), format_datetime_in_joda_syntax(datetime64, 'kk'), format_datetime_in_joda_syntax(date, 'kk'), format_datetime_in_joda_syntax(date32, 'kk');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'kkk'), format_datetime_in_joda_syntax(datetime64, 'kkk'), format_datetime_in_joda_syntax(date, 'kkk'), format_datetime_in_joda_syntax(date32, 'kkk');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'm'), format_datetime_in_joda_syntax(datetime64, 'm'), format_datetime_in_joda_syntax(date, 'm'), format_datetime_in_joda_syntax(date32, 'm');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'mm'), format_datetime_in_joda_syntax(datetime64, 'mm'), format_datetime_in_joda_syntax(date, 'mm'), format_datetime_in_joda_syntax(date32, 'mm');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'mmm'), format_datetime_in_joda_syntax(datetime64, 'mmm'), format_datetime_in_joda_syntax(date, 'mmm'), format_datetime_in_joda_syntax(date32, 'mmm');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 's'), format_datetime_in_joda_syntax(datetime64, 's'), format_datetime_in_joda_syntax(date, 's'), format_datetime_in_joda_syntax(date32, 's');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'ss'), format_datetime_in_joda_syntax(datetime64, 'ss'), format_datetime_in_joda_syntax(date, 'ss'), format_datetime_in_joda_syntax(date32, 'ss');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'sss'), format_datetime_in_joda_syntax(datetime64, 'sss'), format_datetime_in_joda_syntax(date, 'sss'), format_datetime_in_joda_syntax(date32, 'sss');

with '2018-01-12 22:33:44' as s, to_datetime(s, 'UTC') as datetime, to_datetime64(s, 6, 'UTC') as datetime64, to_date16(s) as date, to_date(s) as date32 select format_datetime_in_joda_syntax(datetime, 'zzzz'), format_datetime_in_joda_syntax(datetime64, 'zzzz');

with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'G123DDD'), format_datetime_in_joda_syntax(datetime64, 'G123DDD'), format_datetime_in_joda_syntax(date, 'G123DDD'), format_datetime_in_joda_syntax(date32, 'G123DDD');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'G\'\'DDD'), format_datetime_in_joda_syntax(datetime64, 'G\'\'DDD'), format_datetime_in_joda_syntax(date, 'G\'\'DDD'), format_datetime_in_joda_syntax(date32, 'G\'\'DDD');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'G\'aaa\'DDD'), format_datetime_in_joda_syntax(datetime64, 'G\'aaa\'DDD'), format_datetime_in_joda_syntax(date, 'G\'aaa\'DDD'), format_datetime_in_joda_syntax(date32, 'G\'aaa\'DDD');
with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'G\'a\'\'aa\'DDD'), format_datetime_in_joda_syntax(datetime64, 'G\'a\'\'aa\'DDD'), format_datetime_in_joda_syntax(date, 'G\'a\'\'aa\'DDD'), format_datetime_in_joda_syntax(date32, 'G\'a\'\'aa\'DDD');

with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'x'), format_datetime_in_joda_syntax(datetime64, 'x'), format_datetime_in_joda_syntax(date, 'x'), format_datetime_in_joda_syntax(date32, 'x');

with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'w'), format_datetime_in_joda_syntax(datetime64, 'w'), format_datetime_in_joda_syntax(date, 'w'), format_datetime_in_joda_syntax(date32, 'w');

with '2018-01-12 22:33:44' as s, to_datetime(s) as datetime, to_datetime64(s, 6) as datetime64, to_date16(s) as date, to_date(s) as date32 SELECT format_datetime_in_joda_syntax(datetime, 'S'), format_datetime_in_joda_syntax(datetime64, 'S'), format_datetime_in_joda_syntax(date, 'S'), format_datetime_in_joda_syntax(date32, 'S');
with '2018-01-12 22:33:44.55' as s, to_datetime64(s, 6) as datetime64 SELECT format_datetime_in_joda_syntax(datetime64, 'S');
with '2018-01-12 22:33:44.55' as s, to_datetime64(s, 6) as datetime64 SELECT format_datetime_in_joda_syntax(datetime64, 'SS');
with '2018-01-12 22:33:44.55' as s, to_datetime64(s, 6) as datetime64 SELECT format_datetime_in_joda_syntax(datetime64, 'SSS');
with '2018-01-12 22:33:44.55' as s, to_datetime64(s, 6) as datetime64 SELECT format_datetime_in_joda_syntax(datetime64, 'SSSS');
with '2018-01-12 22:33:44.55' as s, to_datetime64(s, 6) as datetime64 SELECT format_datetime_in_joda_syntax(datetime64, 'SSSSS');
with '2018-01-12 22:33:44.55' as s, to_datetime64(s, 6) as datetime64 SELECT format_datetime_in_joda_syntax(datetime64, 'SSSSSS');
with '2018-01-12 22:33:44.55' as s, to_datetime64(s, 6) as datetime64 SELECT format_datetime_in_joda_syntax(datetime64, 'SSSSSSS');
with '2018-01-12 22:33:44.55' as s, to_datetime64(s, 6) as datetime64 SELECT format_datetime_in_joda_syntax(datetime64, 'SSSSSSSS');
with '2018-01-12 22:33:44.55' as s, to_datetime64(s, 6) as datetime64 SELECT format_datetime_in_joda_syntax(datetime64, 'SSSSSSSSS');
with '2018-01-12 22:33:44.55' as s, to_datetime64(s, 6) as datetime64 SELECT format_datetime_in_joda_syntax(datetime64, 'SSSSSSSSSS');
-- { echoOff }


