DROP STREAM IF EXISTS kek;
DROP STREAM IF EXISTS kekv;

CREATE STREAM kek (a uint32);
CREATE MATERIALIZED VIEW kekv AS SELECT * FROM kek;

INSERT INTO kek(a) VALUES (1);
DELETE FROM kekv WHERE a = 1; -- { serverError BAD_ARGUMENTS}

DELETE FROM kekv WHERE a = 1; -- { serverError BAD_ARGUMENTS}

DROP STREAM IF EXISTS kekv;
DROP STREAM IF EXISTS kek;
