DROP STREAM IF EXISTS t;
SELECT sleep(1);
CREATE STREAM t (key uint64, value uint64, INDEX value_idx value TYPE bloom_filter GRANULARITY 1) ORDER BY key;
SELECT sleep(1);
INSERT INTO t(key, value) SELECT number, rand()%1000 FROM numbers(10000);
SELECT sleep(2);
SET timeout_overflow_mode='break';
SET max_execution_time=0.1;
SELECT * FROM table(t) WHERE value IN (SELECT number FROM numbers(1000000000));
DROP STREAM t;