version: '3.7'
services:
  proton:
     image: ghcr.io/timeplus-io/proton:latest
     pull_policy: always
     ports:
       - 3218:3218 #http port for JDBC driver, default streaming mode
       - 8123:8123 #http port for JDBC driver, default batch mode
       - 8463:8463 #tcp port for go driver or grafana plugin

  proxy:
    image: sensor-logger-proxy
    ports:
       - 3000:3000 #forward HTTP POST to proton:3218
    environment:
      HOST: proton
      STREAM: phone
    depends_on:
      - proton
