set extremes = '1';
DROP STREAM IF EXISTS HASH_TEST_INSERT;
DROP STREAM IF EXISTS HASH_MV;
CREATE STREAM HASH_TEST_INSERT (`STR_VAL` string) ENGINE = Null;
CREATE MATERIALIZED VIEW HASH_MV (`HASH_VAL` uint64, `STR_VAL` low_cardinality(string)) ENGINE = ReplacingMergeTree ORDER BY HASH_VAL AS SELECT xxHash64(STR_VAL) AS HASH_VAL, to_low_cardinality(STR_VAL) AS STR_VAL FROM HASH_TEST_INSERT;
INSERT INTO HASH_TEST_INSERT VALUES ('a');

