SELECT hex(to_string(uniq_state(to_nullable(1)))) WITH TOTALS;
SELECT '---';
SELECT hex(to_string(uniq_state(x))) FROM (SELECT to_nullable(1) AS x) WITH TOTALS;
SELECT '---';
SELECT DISTINCT hex(to_string(uniq_state(x))) FROM (SELECT materialize(1) AS k, to_nullable(1) AS x FROM numbers(1)) GROUP BY k WITH TOTALS ORDER BY k;
SELECT '---';
SELECT DISTINCT hex(to_string(uniq_state(x))) FROM (SELECT materialize(1) AS k, to_nullable(1) AS x FROM numbers(10)) GROUP BY k WITH TOTALS ORDER BY k;
SELECT '---';
SELECT DISTINCT hex(to_string(uniq_state(x))) FROM (SELECT int_div(number, 3) AS k, to_nullable(1) AS x FROM numbers(10)) GROUP BY k WITH TOTALS ORDER BY k;
SELECT '---';
SELECT DISTINCT hex(to_string(uniq_state(x))) FROM (SELECT int_div(number, 3) AS k, to_nullable(1) AS x FROM system.numbers LIMIT 100000) GROUP BY k WITH TOTALS ORDER BY k;
SELECT '---';
SELECT DISTINCT arrayUniq(finalize_aggregation(groupArrayState(x))) FROM (SELECT int_div(number, 3) AS k, to_nullable(1) AS x FROM system.numbers LIMIT 100000) GROUP BY k WITH TOTALS ORDER BY k;
SELECT '---';
SELECT k, finalize_aggregation(uniq_state(x)) FROM (SELECT int_div(number, 3) AS k, to_nullable(1) AS x FROM system.numbers LIMIT 100000) GROUP BY k WITH TOTALS ORDER BY k LIMIT 5;
SELECT '---';
SELECT k, finalize_aggregation(uniq_state(x)) FROM (WITH to_nullable(number = 3 ? 3 : 1) AS d SELECT int_div(number, 3) AS k, number % d AS x FROM system.numbers LIMIT 100000) GROUP BY k WITH TOTALS ORDER BY k LIMIT 5;
SELECT '---';
SELECT k, finalize_aggregation(quantiles_timing_state(0.5)(x)) FROM (WITH to_nullable(number = 3 ? 3 : 1) AS d SELECT int_div(number, 3) AS k, number % d AS x FROM system.numbers LIMIT 100000) GROUP BY k WITH TOTALS ORDER BY k LIMIT 5;
SELECT '---';
SELECT k, finalize_aggregation(quantiles_timing_state(0.5)(x)) FROM (SELECT int_div(number, if(number = 9223372036854775807, -2, if(number = 3, number = if(number = 1, NULL, 3), 1)) AS d) AS k, number % d AS x FROM system.numbers LIMIT 100000) GROUP BY k WITH TOTALS ORDER BY k ASC LIMIT 5;
SELECT '---';
SELECT DISTINCT hex(to_string(uniq_state(x))) FROM (SELECT materialize(1) AS k, to_nullable(1) AS x FROM numbers(1)) GROUP BY k WITH ROLLUP ORDER BY k;
SELECT '---';
SELECT DISTINCT hex(to_string(uniq_state(x))) FROM (SELECT materialize(1) AS k, to_nullable(1) AS x FROM numbers(1)) GROUP BY k WITH CUBE ORDER BY k;
SELECT '---';
