SET query_mode = 'table';
drop stream if exists prewhere_alias;
create stream prewhere_alias (a uint8,  b int32,  c uint8 ALIAS a,  d int64 ALIAS b + 1, e int32 alias a + b) ENGINE = MergeTree ORDER BY tuple();
insert into prewhere_alias values (1, 1);
select '-';
select a from prewhere_alias prewhere a = 1;
select b from prewhere_alias prewhere a = 1;
select c from prewhere_alias prewhere a = 1;
select d from prewhere_alias prewhere a = 1;
select '-';
select a from prewhere_alias prewhere b = 1;
select b from prewhere_alias prewhere b = 1;
select c from prewhere_alias prewhere b = 1;
select d from prewhere_alias prewhere b = 1;
select '-';
select a from prewhere_alias prewhere c = 1;
select b from prewhere_alias prewhere c = 1;
select c from prewhere_alias prewhere c = 1;
select d from prewhere_alias prewhere c = 1;
select '-';
select a from prewhere_alias prewhere d = 2;
select b from prewhere_alias prewhere d = 2;
select c from prewhere_alias prewhere d = 2;
select d from prewhere_alias prewhere d = 2;
select '-';
select a from prewhere_alias prewhere a;
select b from prewhere_alias prewhere a;
select c from prewhere_alias prewhere a;
select d from prewhere_alias prewhere a;
select '-';
select a from prewhere_alias prewhere c;
select b from prewhere_alias prewhere c;
select c from prewhere_alias prewhere c;
select d from prewhere_alias prewhere c;
drop stream if exists prewhere_alias;

