#!/usr/bin/env bash

CLICKHOUSE_CLIENT_SERVER_LOGS_LEVEL=none

CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=../shell_config.sh
. "$CURDIR"/../shell_config.sh

echo "EXPLAIN AST ALTER STREAM t ADD COLUMN c int8;
EXPLAIN AST ALTER STREAM t DROP COLUMN c;
EXPLAIN AST ALTER STREAM t MODIFY COLUMN c int8;
EXPLAIN AST ALTER STREAM t COMMENT COLUMN c 'comment';
EXPLAIN AST ALTER STREAM t RENAME COLUMN c TO d;
EXPLAIN AST ALTER STREAM t MATERIALIZE COLUMN c;
EXPLAIN AST ALTER STREAM t MODIFY ORDER BY x;
EXPLAIN AST ALTER STREAM t MODIFY SAMPLE BY y;
EXPLAIN AST ALTER STREAM t MODIFY TTL z + INTERVAL 7 DAY;
EXPLAIN AST ALTER STREAM t MATERIALIZE TTL IN PARTITION 'p';
EXPLAIN AST ALTER STREAM t MODIFY SETTING index_granularity = 4096;
EXPLAIN AST ALTER STREAM t RESET SETTING index_granularity;
EXPLAIN AST ALTER STREAM t MODIFY QUERY SELECT 42;
EXPLAIN AST ALTER STREAM t REMOVE TTL;
EXPLAIN AST ALTER STREAM t REMOVE SAMPLE BY;
EXPLAIN AST ALTER STREAM t ADD INDEX i c TYPE minmax GRANULARITY 1;
EXPLAIN AST ALTER STREAM t DROP INDEX i;
EXPLAIN AST ALTER STREAM t MATERIALIZE INDEX i;
EXPLAIN AST ALTER STREAM t ADD CONSTRAINT x CHECK 1;
EXPLAIN AST ALTER STREAM t DROP CONSTRAINT x;
EXPLAIN AST ALTER STREAM t ADD PROJECTION p (SELECT c);
EXPLAIN AST ALTER STREAM t DROP PROJECTION p;
EXPLAIN AST ALTER STREAM t MATERIALIZE PROJECTION p;
EXPLAIN AST ALTER STREAM t DETACH PARTITION 'p';
EXPLAIN AST ALTER STREAM t DROP PARTITION 'p';
EXPLAIN AST ALTER STREAM t ATTACH PARTITION 'p';
EXPLAIN AST ALTER STREAM t ATTACH PART 'p';
EXPLAIN AST ALTER STREAM t ATTACH PARTITION 'p' FROM t2;
EXPLAIN AST ALTER STREAM t REPLACE PARTITION 'p' FROM t2;
EXPLAIN AST ALTER STREAM t MOVE PARTITION 'p' TO STREAM t2;
EXPLAIN AST ALTER STREAM t CLEAR COLUMN c IN PARTITION 'p';
EXPLAIN AST ALTER STREAM t FREEZE;
EXPLAIN AST ALTER STREAM t FREEZE PARTITION 'p';
EXPLAIN AST ALTER STREAM t UNFREEZE WITH NAME 'n';
EXPLAIN AST ALTER STREAM t UNFREEZE PARTITION 'p' WITH NAME 'n';
EXPLAIN AST ALTER STREAM t FETCH PARTITION 'p' FROM '/path';
EXPLAIN AST ALTER STREAM t FETCH PART 'p' FROM '/path';
EXPLAIN AST ALTER STREAM t UPDATE c = 1 WHERE 1;
EXPLAIN AST ALTER STREAM t UPDATE c = 1 IN PARTITION 'p' WHERE 1;
EXPLAIN AST ALTER STREAM t DELETE WHERE c = 1;
EXPLAIN AST ALTER STREAM t DELETE IN PARTITION 'p' WHERE c = 1;" | \
    $CLICKHOUSE_CLIENT --readonly 1 --multiquery 2>&1 | grep 'AlterCommand'
