DROP STREAM IF EXISTS t;
DROP STREAM IF EXISTS v;

create stream t (c string) ;

CREATE MATERIALIZED VIEW v to v AS SELECT c FROM t; -- { serverError 36 }
CREATE MATERIALIZED VIEW v to t AS SELECT * FROM v; -- { serverError 60 }

DROP STREAM IF EXISTS t1;
DROP STREAM IF EXISTS t2;
DROP STREAM IF EXISTS v1;
DROP STREAM IF EXISTS v2;

create stream t1 (c string) ;
create stream t2 (c string) ;

CREATE MATERIALIZED VIEW v1 to t1 AS SELECT * FROM t2;
CREATE MATERIALIZED VIEW v2 to t2 AS SELECT * FROM t1;

INSERT INTO t1 VALUES ('Hello'); -- { serverError 306 }
INSERT INTO t2 VALUES ('World'); -- { serverError 306 }

DROP STREAM IF EXISTS t;
DROP STREAM IF EXISTS v;
DROP STREAM IF EXISTS t1;
DROP STREAM IF EXISTS t2;
DROP STREAM IF EXISTS v1;
DROP STREAM IF EXISTS v2;
