#!/usr/bin/env sh

# Execute the given argument list as a command. If exits zero, prints "true",
# otherwise "false". stdout from the subcommand will be supressed. stderr will
# be forwarded. This script itself will always exit zero.

# Usage: __boolstr [cmd...]

"$@" 1>/dev/null

if test $? = 0; then
    printf "true"
else
    printf "false"
fi
