{
 "title": "Hackernews Live Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "# of Stories",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "sql": "select count() from story" }
   ]
  },
  {
   "title": "# of Comments",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "sql": "select count() from comment" }
   ]
  },
  {
   "title": "Most active commenters",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "sql": "select `by`,count() as comments,emit_version() from comment where `by`<>'' group by `by` order by comments desc limit 5 by emit_version()"
    }
   ]
  },
  {
   "title": "Stories",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "sql": "select _tp_time,id,`by`,title from story"
    }
   ]
  },
  {
   "title": "Comments",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "sql": "select _tp_time,id,root_id,`by`,raw:text as text from comment"
    }
   ]
  },
  {
   "title": "Stories&Comments",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "sql": "select \n    story._tp_time as story_time,comment._tp_time as comment_time,\n    story.id as story_id, comment.id as comment_id,\n    story.title as title,comment.raw:text as comment\nfrom story join comment on story.id=comment.root_id"
    }
   ]
  }
 ]
}