-- Tags: no-parallel

SHOW TABLES NOT LIKE '%';

DROP DATABASE IF EXISTS test_01073;
CREATE DATABASE test_01073;
USE test_01073;

SHOW TABLES;
SELECT '---';
create stream test1 (x uint8) ;
create stream test2 (x uint8) ;

SHOW TABLES;
SELECT '--';
SHOW TABLES LIKE 'tes%';
SELECT '--';
SHOW TABLES NOT LIKE 'tes%';
SELECT '--';
SHOW TABLES LIKE 'tes%1';
SELECT '--';
SHOW TABLES NOT LIKE 'tes%2';

SELECT '---';
SHOW TABLES FROM test_01073;
SELECT '--';
SHOW TABLES FROM test_01073 LIKE 'tes%';
SELECT '--';
SHOW TABLES FROM test_01073 NOT LIKE 'tes%';
SELECT '--';
SHOW TABLES FROM test_01073 LIKE 'tes%1';
SELECT '--';
SHOW TABLES FROM test_01073 NOT LIKE 'tes%2';

DROP DATABASE test_01073;
