DROP STREAM IF EXISTS t1;

create stream t1 (`cA` string, `c1` string) ENGINE = MergeTree ORDER BY (cA, c1);

insert into t1 select 'AAAAAAAAAAA', 'BBBBBB';

select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);
select count() from t1 where c1 in (select 'BBBBBB' union all select null);


select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);
select count() from t1 where cast(c1 as Nullable(string)) in (select 'BBBBBB' union all select null);

DROP STREAM t1;
