SELECT bit_and(0, inf); -- { serverError 43 }
SELECT bitXor(0, inf); -- { serverError 43 }
SELECT bit_or(0, inf); -- { serverError 43 }
SELECT bit_test(inf, 0); -- { serverError 43 }
SELECT bit_test(0, inf); -- { serverError 43 }
SELECT bitRotateLeft(inf, 0); -- { serverError 43 }
SELECT bitRotateRight(inf, 0); -- { serverError 43 }
SELECT bit_shift_left(inf, 0); -- { serverError 43 }
SELECT bitShiftRight(inf, 0); -- { serverError 43 }
