ATTACH VIEW columns
(
    `table_catalog` string,
    `table_schema` string,
    `table_name` string,
    `column_name` string,
    `ordinal_position` uint64,
    `column_default` string,
    `is_nullable` uint8,
    `data_type` string,
    `character_maximum_length` nullable(uint64),
    `character_octet_length` nullable(uint64),
    `numeric_precision` nullable(uint64),
    `numeric_precision_radix` nullable(uint64),
    `numeric_scale` nullable(uint64),
    `datetime_precision` nullable(uint64),
    `character_set_catalog` nullable(string),
    `character_set_schema` nullable(string),
    `character_set_name` nullable(string),
    `collation_catalog` nullable(string),
    `collation_schema` nullable(string),
    `collation_name` nullable(string),
    `domain_catalog` nullable(string),
    `domain_schema` nullable(string),
    `domain_name` nullable(string),
    `column_comment` string,
    `column_type` string,
    `TABLE_CATALOG` string ALIAS table_catalog,
    `TABLE_SCHEMA` string ALIAS table_schema,
    `TABLE_NAME` string ALIAS table_name,
    `COLUMN_NAME` string ALIAS column_name,
    `ORDINAL_POSITION` uint64 ALIAS ordinal_position,
    `COLUMN_DEFAULT` string ALIAS column_default,
    `IS_NULLABLE` uint8 ALIAS is_nullable,
    `DATA_TYPE` string ALIAS data_type,
    `CHARACTER_MAXIMUM_LENGTH` nullable(uint64) ALIAS character_maximum_length,
    `CHARACTER_OCTET_LENGTH` nullable(uint64) ALIAS character_octet_length,
    `NUMERIC_PRECISION` nullable(uint64) ALIAS numeric_precision,
    `NUMERIC_PRECISION_RADIX` nullable(uint64) ALIAS numeric_precision_radix,
    `NUMERIC_SCALE` nullable(uint64) ALIAS numeric_scale,
    `DATETIME_PRECISION` nullable(uint64) ALIAS datetime_precision,
    `CHARACTER_SET_CATALOG` nullable(string) ALIAS character_set_catalog,
    `CHARACTER_SET_SCHEMA` nullable(string) ALIAS character_set_schema,
    `CHARACTER_SET_NAME` nullable(string) ALIAS character_set_name,
    `COLLATION_CATALOG` nullable(string) ALIAS collation_catalog,
    `COLLATION_SCHEMA` nullable(string) ALIAS collation_schema,
    `COLLATION_NAME` nullable(string) ALIAS collation_name,
    `DOMAIN_CATALOG` nullable(string) ALIAS domain_catalog,
    `DOMAIN_SCHEMA` nullable(string) ALIAS domain_schema,
    `DOMAIN_NAME` nullable(string) ALIAS domain_name,
    `COLUMN_COMMENT` string ALIAS column_comment,
    `COLUMN_TYPE` string ALIAS column_type
) AS
SELECT
    database AS table_catalog,
    database AS table_schema,
    table AS table_name,
    name AS column_name,
    position AS ordinal_position,
    default_expression AS column_default,
    type LIKE 'Nullable(%)' AS is_nullable,
    type AS data_type,
    character_octet_length AS character_maximum_length,
    character_octet_length,
    numeric_precision,
    numeric_precision_radix,
    numeric_scale,
    datetime_precision,
    NULL AS character_set_catalog,
    NULL AS character_set_schema,
    NULL AS character_set_name,
    NULL AS collation_catalog,
    NULL AS collation_schema,
    NULL AS collation_name,
    NULL AS domain_catalog,
    NULL AS domain_schema,
    NULL AS domain_name,
    comment AS column_comment,
    type AS column_type
FROM system.columns
