DROP TEMPORARY STREAM IF EXISTS t1;
DROP TEMPORARY STREAM IF EXISTS t2;

CREATE TEMPORARY STREAM t1 (a int64) Engine=Memory;
CREATE TEMPORARY STREAM t2 (a int64, b int64) Engine=Memory;

WITH b AS bb SELECT bb FROM t2 WHERE a IN (SELECT a FROM t1);